---
apiVersion: v2
name: garage
version: 0.0.1
dependencies:
  - name: garage
    repository: https://helm.charliemaiors.dev
    version: 0.7.1
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
