app-template:
    ingress:
        main:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:+rnSzE4qYLNe,iv:jZbfAZ9v7Bucbqg/WSbsl87z37GZjNOhB7SzEiFZoDs=,tag:/3s78vd5riAA3deni6/H3Q==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:oP2jOsRYL8jqbFGB9V/kdsCP83nyv/0mj8Lh2Yx0,iv:M8OJohl/oggSNbgCoYyH018Bi6dxHKbDnqDl6RmZ0cg=,tag:5aIi4JUDKbwLT0XM6KU0Kw==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:DOboC3YKGTvJINuFHKlEgEj+v+krVN1ViWOE1K3ohV9mrSPneLM9WgQsJomC62RLD2s7uMkLNwV7nDrBBqMokBrMVbU=,iv:i10VY4Mk0ONuZ2T4b4F1te16K2Nd9TC0koa+CJpY9MM=,tag:hgHz+NPTfisc9fee8fYI+w==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Nlc4Y2R3c1NYU3JTYXZL
            YW43M3l2S3FQeGlidU9ZUzhlbTh3RElQTWtJCmlKWXpyQXIxMVkrdXFXQ0ZUNEdy
            T3ZMTVJNdityYnpBWVd3MTY5bDlqZ3cKLS0tIGtKWU5xVHVIMmNwS3ovNm9lOE9L
            aFgyakZNR1lSSUlxSFJvV1JSZHhtd00K7YVlfL74Yd+Ysgko5bEBV3mjKFvsjHCz
            T8t3InAzmTpWc4eR81GEZiBh/Xq/9FhMWLHMh9XcRYZq8YghHJn/AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T19:57:04Z"
    mac: ENC[AES256_GCM,data:w+6x4B+aA/LAGPgFTma94RsPcWCyRoKDXT46qPtSOQl3DuHv8a4MAvbElcyxLTlaLrxVWtnvSPQK4REsFLUoG5fSkC8+fUtF3lWRi+14bnQaxY+4BwZVJK4hz1xuEHXx6kFH3QKbGADXWv8Bu1C6ODJiicjKeUWgAs0WzyCRXK8=,iv:MyYKIXvlEPGHsgSsGyxGvrm5gGcut1AKk2OFk7NzK+k=,tag:gzC4KEj9D6/DlFgprqIsgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
