---
app-template:
  controllers:
    databasus:
      strategy: Recreate
      containers:
        databasus:
          nameOverride: databasus
          image:
            repository: databasus/databasus
            tag: v3.4.0

  service:
    databasus:
      controller: databasus
      ports:
        http:
          port: 4005

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /databasus-data

  ingress:
    databasus:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/name: Databasus
        gethomepage.dev/description: Database backup tool
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Database Tools
        gethomepage.dev/icon: sh-databasus.png
        gethomepage.dev/pod-selector: ""
      hosts:
        - host: &databasus databasus.mdeleon.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: databasus
                port: http
      tls:
        - secretName: databasus-tls-cert
          hosts:
            - *databasus
