---
apiVersion: v2
name: vm
version: 1.0.0
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.70.0
    repository: https://victoriametrics.github.io/helm-charts/
  #- name: prometheus-snmp-exporter
  #  version: 9.11.0
  #  repository: https://prometheus-community.github.io/helm-charts
