victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:Gaz7n63D5V+tb+8e+W4rOGelDGOcWjbPfsKn5nqKAZw=,iv:NvE+R/9vGRvw00B2H8JQ8vMelE1QqBLCnkjdPbWNuq8=,tag:/WKw6t3r1rJIvhc5tLqnPg==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:3mhqI3S1OHZ556bvUYYA2MgVaaY=,iv:BldjJOuMHd4xcD9FJZ7LpBSKR4t87lBawVmNG1elnEE=,tag:pDy8Qs9A7Rlbb36soxhQpQ==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:74LAUA==,iv:xhIRFBS7i2Pv5nk0XvRWYY5CKTaPlZJrhq6SiFkH/aY=,tag:2jLMoBbFK8PH799vVi7VRw==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:77gDuiq7xoSUptIZmVuDGqCXItOpGgyiDxSr,iv:M7I5x+vD4mmgw5ddvU1HZzWybJxnksE8EIKRcd9rq7E=,tag:xxeqzmmnAe9jaFPX6OsJKA==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:EmBMiw==,iv:f9bSL8K5g6fljDN4lXhEcpHanQ9bpYXYOTJkj4FWbac=,tag:W9LG+4M7eHsFEh/f+epXgw==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:u1Ru200y,iv:toQ8WuaWXc0KSiqbdiASz2PRZMgTc8rzDfVLHhXRQBE=,tag:IEjZyqGoaPTl6YQbs9KCvA==,type:str]
                default_theme: ENC[AES256_GCM,data:hbZvtaye,iv:3rU9SIMjmdQ+O1ctzS9LQhxs+/q+j5utjPbgDc7REQc=,tag:6UsKvumHv4B41bw3+Mst3A==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:rNoADA==,iv:dRrcgO4B019jsFhyeHFZSkBv1QsVx+vRVkDWxCu025Y=,tag:TgX18VnEv6ae/WO2gpkTeg==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:EsDPEA==,iv:vRCTSwe7hDTnv2CWgWij/JMGz9012h1TawJu6G2Do0c=,tag:Ra8Mz5hgJ1sdVRZwGA0yVQ==,type:bool]
                auto_login: ENC[AES256_GCM,data:7EVJSZM=,iv:FAWO0HGfFsJd40MqFdQEDdo07wy2XXZrmDaU+spMvAM=,tag:7/FfRc053PLCqdTgjCeG/Q==,type:bool]
                name: ENC[AES256_GCM,data:YJjg1NKtl0Jj,iv:BA6mrCapRXUiN5IV5qNMgzqJ3Vlb6MdXoENCd8AnLRY=,tag:+IJOu0yw/nY1UqXux8z8fA==,type:str]
                client_id: ENC[AES256_GCM,data:AJJKGR2U3yHvegd+HnyeSTxNkJ5K8aWBNeq1Mr0C3Djd7ZtG,iv:k4LvPzxcpZkfk3j1odBOVwoYBFFMybXIc9kcz0UIPi8=,tag:AOahvf/jgiKyts577b4REQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Ry6G7mlQ54HjKivUoZ/EnQ==,iv:3HEeOe6jd2JtmpxUdTF8dTKK8bD/N08sJ2bfqRP+/nc=,tag:caU5QOYWlMhJnIGvvje8qQ==,type:str]
                scopes: ENC[AES256_GCM,data:UC91hSnhNRfDpwUbdBi0ttzXWZFwrHjfbSP0xG3K5YoCcyQ=,iv:p58di1WQkpAFbj6mVbWcurHqnNHKMKDPnvk83m/4Vuo=,tag:PZ9tUrWmaZaPpdaSCZehfA==,type:str]
                auth_url: ENC[AES256_GCM,data:Jzor4uCRHh+so6EGN34sIsDptQ38kaS1bhG8MOL7oRqUeSx9,iv:VGD9TfmwVzonUtCB/I97xrTxSSMJ3bzVWsNfNuFA/9Q=,tag:OYlYkNX2J9shLGxROhqPOA==,type:str]
                token_url: ENC[AES256_GCM,data:wY85jCmRcn5hV7pJ5RJumk92QwMLMCgyN8Rfg7N2R3takflCphKqhPM=,iv:4I5J3TsxiOKfkzmxjkV/nTQQNI7UYurEND0hkUFoOjA=,tag:ePHpk+38YnWpUkt88mWb3g==,type:str]
                api_url: ENC[AES256_GCM,data:jREijoYMlkL3KjwnZ6K/Wx+xqTn71HhmPMboonmh+vlhvdnJnENx901GHqg=,iv:2VPpdlK3nvmV+p+5+ckDi1NorOErCsmkqhCrG+OwXFU=,tag:yqDSSt1vTDeqa9x//jfjvg==,type:str]
                use_pkce: ENC[AES256_GCM,data:c8o1gA==,iv:+2ohtq8leMuRB/5xKUwZnrNtSf33QNgAVXB4z+spSx4=,tag:wFM1o9C6oXdfBV2hE7BsLw==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:WhR2GA==,iv:WnQ3D400ci4U59jvHQghdyeilL0tsUhAv7a+GHfJw5Y=,tag:mBtoOt38bwz+iBx72pmduA==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:wWT45lY=,iv:DiDCBrtWsa9wB4dxdxtkqswQ/U/IzsJl0+j87D4t4LI=,tag:WMgxNry4iWPAOglps2XXog==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:1l5spI3q9YJsMkIBW1jXV1FqzKEUiCEEns8yPBV2QDRlo14AMmNzalmcTcQ7IsY=,iv:kCHVtAT8DlCj3BSZD086d4MK41XjzwfAsu6CEZidNlw=,tag:HFqQexN88qGGapfl8/4YAw==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:yP7aNn9q3c0fBJptoUGgGVuH28QMVvGIL46UFCi3dqVyP7XwKuFxhB5m9OD7HTtm03J1ZtaXJ4kHjuwdiNlD6Vm4MukjBwQlwRZI,iv:jgOYN57WbjeZge8nY9zmtnAwd5UPOEydgJOUoB0lPzk=,tag:069qadheO6uzSxaMzAxKKg==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:RcOb/Q==,iv:A48z4OjaUMSlJZtC3Lcu15AE7Wx8HY1EYSV7a3NxJb4=,tag:C97Er1VHuF29Cvn824Gkdg==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:Y4EGEQ==,iv:uCBlVxhvQ4VWXgpR3lcZoSp5UdOwLAu307EFICEX2oA=,tag:IM6J6bzLMTE4et4bzauh5Q==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:MAiu07UMP0r3Nq+a0cM=,iv:n39eFZqJ6s9YoRoHVfid0B3mKRlsJ4O5SJJ3Hajy4Tg=,tag:oGQggYOenO4AV20WOlNyJA==,type:str]
              targetLabel: ENC[AES256_GCM,data:Nl/Ys6rDaIU=,iv:jo7nLj6ZSMqaWCgSo4p7nj6qMdffdmrgsbU/FM3O9Io=,tag:Dw4IXYK9psifHNleuioEIQ==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:13pGb1oD,iv:db0TsPoCKd/phJbQekAlFozv6ZCPOimdAigy9gK6DIM=,tag:3gDT7C1EYqruUpaHs3bbYA==,type:str]
              name: ENC[AES256_GCM,data:sfOIuYxTcS0=,iv:4AIZFr6rdR9kesFteUmHHSGS08dTISuSgfDU+vop17M=,tag:hn40m3T+gH/hIeqKIPS5hQ==,type:str]
              target: ENC[AES256_GCM,data:p19UdXkkjQ7FCoJe6A==,iv:sQhmFlpWdMZT1wcbOd0itTC5ylpr1hxT4j1SpHkIhKw=,tag:KelvZwobY1tmOgpCKHxMCA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYmFJVTQzK3dWazJtOVNz
            bTBQKzRXbjZ2YStjd2lUWkE3MTVma1dJeFhjCkp5cHRwaGZHQUdlVjBCZ1dLbmNT
            L29zNHZ2UkJYWHZWVG1YOW5BRVlqSkkKLS0tIDFCQnBpeU9ubTFBS24rTHlwME92
            NHhjcnZmNUlFaS9EOEJPVHB3QU8xYkUKLtEEH5S8CxDn2QSvUUv+cOJgXNsERXNJ
            1JcEjImv8wvem8TVqv+HoFjPEYizBI1v68VM7KOf7sZVhHZCX9vcRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:16:13Z"
    mac: ENC[AES256_GCM,data:/KL7wQTq43KIgEWfXf72/4e17fIT3culXLsMUln867+Djbukysqep+tfgoLo/Zx8muMRHkmIUYyt5JejbkxgSrjbqPX3owRvH/rG+ywv9U4ttq0g2hGOObbnx7rE5K+97xd5uFZAOjdGJ8R+lB9w/7oVupPxdPIfYTfWXgIhLNg=,iv:JIpelYFXWaCS5GrZ+m9FJkydq1vAvxUjD5UymJwuWos=,tag:VEMMv7R8GRFJA7oj2exIlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
