victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:N1WYrxiv0iqdWn3lx+otwlwevaeWuVewaNyL23oA5jM=,iv:1qUs+3liuxm2YeIZZRNvNmW9ECc1JgeZWZ2PCPlGvdI=,tag:12n5hiUJ0pa0+XlgEO2WTA==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:loMy1liKMgyG0ga5wK2njN6An7Y=,iv:o7wfMZ4TRSnmG5C9hzGNAYOHftfzH4EZBe7LGJOQ2l4=,tag:fOYwQvQ3jP+eiqJPXVbRDw==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:9epXvg==,iv:sEXhvMlLWOxfsfLOb8OxgeJvdkRiDjL0JGfXGbG2Qck=,tag:khmNZdNe3S+ulstP3TvjYA==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:M4Gesz5v2uWSluuIx5skK7GYUaZ7vOOJqCxZ,iv:ewKFVAf1szT3vEMZmJOEsR45/dV38PohLC2mK0UISuU=,tag:02zqB1jB6TsdxwIIzhU9Ew==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:ZXq41g==,iv:uRn0ynfRetEFWXQXmmdX7NTb5tGGf4wUm14lzxXmU9I=,tag:1lgqc/V3BJzrGVe8Zlk8BQ==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:W4OxInbN,iv:sDG9qSnpSC7uzx6dU+/M/EsoPpRI/G5uO2qEbI/5rUE=,tag:7i0+Fi3kSri34VrPTIHC4w==,type:str]
                default_theme: ENC[AES256_GCM,data:9XU6GsCe,iv:XbCEaHyebkZkZ5C7pJM/8pPUOCDXPGkv9ywOLBWHcHQ=,tag:bHvGr87wQGQ8zCHKIYc8/w==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:TPORLw==,iv:dz3nrWpUo88rckYOCl5ix5j30ZNEUPAOrRdJEkjH5l0=,tag:iAPCcB4v6I9beOCAuu9bww==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:U+LiCw==,iv:fz6Jdo8BzG81/Xs8tzAQpDHEfRFVEL8ohwz54jE7UVc=,tag:1onEWvmaidBpKA8gicM+hA==,type:bool]
                auto_login: ENC[AES256_GCM,data:v/wBjH0=,iv:bfv+52eyT5GOrJVukViA1ZjSBBvqLhiJ9Gd+C0UiRJk=,tag:rOKdRuUKw/hsxWBrgm9qZg==,type:bool]
                name: ENC[AES256_GCM,data:Uzg+gbNQ4LA4,iv:4hC038b6J2noDfOIKoCmCREroKC5ALvOhFGr4JznCjc=,tag:7LVlaeSTKkoKjN42gzxv9A==,type:str]
                client_id: ENC[AES256_GCM,data:OqU/fRp5rgsv+rSnqr89cAkPq4etJ96V+u0tBpaEMs91FZmp,iv:SMfkG58nciP3Q/kzqkTr0h7TZzrVS+G/cTLOBX8OZG8=,tag:wFanJNDdvfaYkQuucPiFfw==,type:str]
                client_secret: ENC[AES256_GCM,data:wGKVicqt55a8/vNDmaroXw==,iv:1GEAriOHr67iZLTGAKT6J/iW/OBefO8caPfVx3E6MHc=,tag:IshKbJidvt8bRRYvrn5+9g==,type:str]
                scopes: ENC[AES256_GCM,data:LYjV+WpVzwM3TxLvn+/0KtUvlcNjF677+RSH0BMYDStjA/M=,iv:mPY+yZmVmNujB4mQm5nqWFpbeRvxp7Wg8DVIlVr7GPw=,tag:s2QSa1NlE/HGm8Lv89LRrQ==,type:str]
                auth_url: ENC[AES256_GCM,data:4lyZqqtMJqdG6iGOwZPONvDc7rlnq4p/Yd2zkuuR0bsgSOPB,iv:V/xvJldzfJTE8RcJ5aDeGONyIgDkCj99TSH7Y0KUa0c=,tag:bUA9Wf8rKMkQqm5UqvC4Fw==,type:str]
                token_url: ENC[AES256_GCM,data:iMInUk5XVnGuyRGH2rNg+eWDHY28IHN0aRAbpzm7gTGPcxnwDdRJeG4=,iv:zXLAZEoEdwVdJ1pDgFkgCwBNTWfqofPbCXSEj3Kv1qc=,tag:nkUNoLS7kYfmnCiR02a3JA==,type:str]
                api_url: ENC[AES256_GCM,data:HCqG7Yo/LOWOE7nKRD7k+Gjhql75MN348I4Cm/Bvq/Igqmq6OFtsT0lFxfM=,iv:z2BaomAWOfPAa7Nqk90SjC+p9bq5mjk085MJIxPfJNU=,tag:4kSlQ/AKoh4Lo9Jewy7Zng==,type:str]
                use_pkce: ENC[AES256_GCM,data:niMSbg==,iv:ln65ETsf+rAMYYrHnENqTRvdtF1czXACniRdmfqD16I=,tag:ixf7HhgDUJg1z83ILltD+A==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:MOmMCA==,iv:YGn+6+r2UPAYEq2JeRdxj9WAshPkym6iVfMM1qh7X+Y=,tag:K8eSP+oCNeN03nIA+MkZcg==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:BEJSwxI=,iv:yYcunGdpTnvzq7R6X8QOSkl1ymNBmAStWg7IBBUFFzw=,tag:RrCg6iFHQHmKK0R/TdD+VA==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:e2a45syMvstxFSUMJKW5FVGeDic/qAsNK0wh7QM9/42sK51w+uy1xTZ9pYzskgU=,iv:gn009ry2hJBeupDTdJ1ccFcM+qBFhmVNLjd/Nw4FPcY=,tag:cNDv4pr9Zxca3cIvlwBjgQ==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:Dt+/RkUgfOEEzWp2+4/3dkewOTAYIIgbrUZqd1DdiQ8md34cZEw3bKgqtFOgDpynEuEpZj9euefPn1Svgw2ZEAXm+GDFmDd3iLXh,iv:nXs2hoHHH1enL0gf0W+mNj9gD+hCx2cKhUUMwBJpeuc=,tag:1giO9GAQ/E647WT1Bls2MQ==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:uy6AOQ==,iv:taKJHORtY6ryfya+3hjQY4AczaxxlI7RjlAfcJfZF+0=,tag:gX9ksQpBa2PBAvsbKerHmQ==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:S1witQ==,iv:+k0jBLLJ51gaJsMOUyKAFT4f/HXmgergs5fzwE7UcVs=,tag:fnzancglyAxk8m3Ji6itAA==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:miVlmFVQpXnq8Gccys8=,iv:EZBrynJoBKHn8l0FVkO1qmReR2o5Q6uIvHBJOzhUrMM=,tag:E7TpeJlLtuczgVW8t9wezQ==,type:str]
              targetLabel: ENC[AES256_GCM,data:yFg4ZI/cZRI=,iv:GYTADNGTv8G0QZZO6yGDF8SdPzYwgfJzmayE0aX36fA=,tag:T4JesNOURlelgdz2gBeteA==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:4NRx02hl,iv:x3xoE66oqzxREjEEgPTb2LRcGcklk5k0Mrx7LUByVdc=,tag:srBN3oKqWPEL6SLwxOovfQ==,type:str]
              name: ENC[AES256_GCM,data:Aq1Jy6Cbwt4=,iv:ysqfHQogyTxRlu1EQVJbnd/BB33TmcVPtzOZLoyXITw=,tag:xgrkcngGsfiHf/HOUhtGXw==,type:str]
              target: ENC[AES256_GCM,data:3zVfWsLrpYd1BQSXLQ==,iv:Ueye9TAx33+QYEo+VmTH2pQXw+xuJKBnc4+07y9E+k0=,tag:BgANZcXejqBBgxA1Q4UzCA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzazNrcGFwRXJmNHJta28v
            UVRhQThZT29nMW0xZ0hDY0RsOTRzREtUc0ZNCkFibEIxenE0a0xPNUFEVzkxd0xK
            Z0E2eUpWTUF1eWtqeU5BSzd2T1RGUGMKLS0tIFRkYitVOUw3V2tzTFdjZVQ4VTJY
            S1E1TkZ6N2dmMmY2UHFoU01pR1JoNDgKr5zfjUE+JukoS+/QEhWkq45OVevrstQb
            tRuSN8hKOXEX98IFM0u25CyOsFsQ9L6Z4ETNZwJLJ8zAwG2zyuAh5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:23:39Z"
    mac: ENC[AES256_GCM,data:3KHSL4nJV7gPRJpnrCeUyTNruczO9M8fSfBStICuP2s+DHfbWNR4rlcs5yaUiCi0QHOCoNlHa7iUwBRcbCMBMZTSLK15bkgXo0FcA/jbeo6l5HjU17z0dLodc9OCDbR/rZAewVHrR+AxAvedDhCqGixhV8OJC8pw+KFyND1yxx4=,iv:EQn+uT3kPA13DpCz7EAwkDL5Qitc2MXoikn0yTseYf4=,tag:QIx0O+G2b9omDpWT6fiBww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
