victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:95o9utNP5FnkYq22jeN1aohTG8lv/NuumuuUdoThvb0=,iv:IDUOSN6cHVhY58FoBk77GM4tz7xMwq2yV2rNKiI2b2w=,tag:OXFHgWstxHD7zgvnI0xZfw==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:xU4ATiQ0qrLZfUzeXwYSomim/bA=,iv:9TMt51ABzx2TbubzAz7E4dfqwDWZmDM3DPX7OSvprvU=,tag:wmro4GOLXWgsTr5hP6wcUA==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:Pm0FHg==,iv:dcc+ubPxGg3D1V5NrOjkpjqMcquL1KprY9be4VOOvzs=,tag:ZYpzHQLAjHIy7oxPWZPO0g==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:RIt/dlYXUzb1ERXW+PHFD2K5BdZ6+SbRm2oi,iv:Ns74jH807VlyB7udD/qGQ9QFQw34rlIkPGHfAu6yJaI=,tag:wI5A3sbVji69IQnqc79PpQ==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:OVVhng==,iv:ENm5NLdrpu9nXoReyJoS+3b0vKpGPZ+xZGuGEKAMj3E=,tag:Impdd/fGY7USxPhlyW2qzg==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:UlYZ1oCx,iv:qCNi15GTH/j/GGpz+LBpURvwGvOK3bZm4Bpuz1pT3Us=,tag:YRsBzMpWDcThSTbATZLCIg==,type:str]
                default_theme: ENC[AES256_GCM,data:wx9yuO70,iv:rSJ2twYSR/D3WqthfnDKsAfnseDu6L5zmhAM6RJFKK0=,tag:OyOab2x6BnS2atTpyBkfxA==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:BW1DpA==,iv:HQMLEx3vveUbV7Y8mV9hcIjuPxO2D01CNlBpaNweNEY=,tag:hZwX0fTFElY9B+Q/3s6OXQ==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:wbUqnA==,iv:zdO4wX0sb/reuYnR0csdoNz2hdWZ3YTbxaXpfhGYRM4=,tag:xtmdEWHL/qhr4fg13Sv8tA==,type:bool]
                auto_login: ENC[AES256_GCM,data:0z4FbUY=,iv:c/fjGOxdo/Rq8AlOK2cKkZqHCYe+yqIr9s3RLQ1WiMI=,tag:2BCUMzKlaj/VTl1mI6Iq/g==,type:bool]
                name: ENC[AES256_GCM,data:OejjFzlODYzc,iv:YfGqS0Qczw7epWyYoEc+U4qQop4+WkmGEuQ7CJE2MZU=,tag:7eVbyaFGk09dgbXUqZZ3Tg==,type:str]
                client_id: ENC[AES256_GCM,data:PzDf9IgIyqkl4e9xDxCVb9dpeoLUkOvPduHlScJKKnJSzeCp,iv:Omvr44bUWAZFHwFGPQsE5OXnGgXNrYAOgYsEfnwTmlI=,tag:ZDcZ04Bbs2DEXVzTkmpYMQ==,type:str]
                client_secret: ENC[AES256_GCM,data:f/NzVQdua+UjRczOHUOpAQ==,iv:wVO6xZXRlg0C0b9yNsNYiGfzsXNQA7MNcquMtEVF438=,tag:b1gMIQcXt+g/IQ6OUW3dTA==,type:str]
                scopes: ENC[AES256_GCM,data:5Jhx/TFnLBXP3P1CDVpXy0KF3Lgu4le7TS6pO3aR5+YR8Ws=,iv:9o8iiiuieqyOJD3iKawEdrNXJjPFI/VLTN//zgkMj0I=,tag:kWdY7MMc2HRHB3vPnN8Orw==,type:str]
                auth_url: ENC[AES256_GCM,data:dPQ4gDsbbr1aN0TqAwfWZI45AZxF/hDp7Cv58+gevxJXgV+D,iv:Tq2S4HjWv2Ossps8cChfgdolJRRRhQcF5oe/vEY1+Ek=,tag:JU2H9hCz5mM2Sf0okHfjIQ==,type:str]
                token_url: ENC[AES256_GCM,data:1jzhHHloARTkQI56i61eDnBeRxIsEijAo3lxLcdPZEw6djlKL6VE8Lk=,iv:RufVc3YJmjXAp1fFjQZaawYtP5wkTu181hot4/CAgwM=,tag:r2GjPwyH78xH5s9MFt0GRQ==,type:str]
                api_url: ENC[AES256_GCM,data:xlsk+svACz9jrjRciakukyiuLOqVZlR/vGr8kDlgql3K6KXFaP3ZkNOrZcA=,iv:sV5AX4BIEcuM6UI7fbflEndCaQiTZZm49BA25oGDXG8=,tag:BQNP3ZAtzpVJSQGKsSRVpA==,type:str]
                use_pkce: ENC[AES256_GCM,data:b5+uug==,iv:OK1SFXfjO4tQlVC+Hkn/5TDfTJeyIRCyhy8d94FBPrw=,tag:Hpk1RDtBDXuKCXIgLyh+5A==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:7k+5kQ==,iv:Pg+DO+Bnh74xOSqYQ3Haer17NxGUBjs0lQGtrWZPd4g=,tag:CSgGhuV2w84zzuXSXR4e/g==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:Y/Qcg5M=,iv:LwksRSZ8Cfq52uMvyr7wqjd9XAPfFbMyTqp/rI1+s0Y=,tag:hETx57hFsXpvIHoY28hMOw==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:jlU03o4x09tOQ2D9s5ekgTWABO6PfcSZdLtgyqarcQc8u5UrnUv50HUNGPfew00=,iv:BPezdmMIbDbJHEnIgeNn5jwTrB5Jxw3amkBFA6NZTs0=,tag:GR/4GMcTO99NVl13TSS+Hw==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:ooef6BJt5Rr2lHtEkXTUBdhX+OLRNRmhfEQPmUJ9KFqNNoHfUPuxW48Y3va41s2Gp90RaxXlIdLsM89u860huoR0FAP2rw+GUQWa,iv:TtLHDLnLNDsLOms0/0ZG6BON7t5XNMFDtm7M+6sjjA4=,tag:8svXgaaYhQK9CvkCmmxmUw==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:UMvCAA==,iv:o/odFeKRG8T3j/8G+oJFmIxoR23txngQfasu1pnbMj8=,tag:ijHZ8aD25qbzvF6xxsBz+Q==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:Bfl+Rw==,iv:5JYBXT0kuCYs6uopc/UmoLhdTAWKVdBh3jGGE5M+/jE=,tag:DDChtlljPEq+dYC8kkRZMQ==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:HTnFNtK1JIPL2BelWvQ=,iv:HIUfE5MVfokY2IUG5+zrqsyJMRDJQN4cYkqjuuHShY8=,tag:G1Kg6iFOfKcQzzN4q3bBoA==,type:str]
              targetLabel: ENC[AES256_GCM,data:Ct9TS6IVFDs=,iv:IUIoCBp4pA4Q3MMxSBw31fOIbfPWeH5qgoU8kwT5obg=,tag:Dgm+meRXeu4CiNbMKN+KWw==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:zpxg3/MS,iv:cywAC+oALRLCSD7JlHi7FFFawvcKO04AJYIRieWgPHg=,tag:iYyrbfmwbXTWrnrbR/0QNg==,type:str]
              name: ENC[AES256_GCM,data:4oJTM2ajxqo=,iv:yGLiyQz6ynOL8/4awaCuac84iFchHh4fgZ//+krh6Rk=,tag:/mfkB6OhihsW5f/6g5DcJQ==,type:str]
              target: ENC[AES256_GCM,data:FDyu0jVAw4nJNhIqxg==,iv:hT3L0IykWpfrCjBELCexKfWkFNwUY75jiNMMIvD2T+A=,tag:q6lWBVMdv2qTnA619sAJMA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa1J4SXJLUlgzcndqRGJw
            YkxVWkdrOVNpcTQrMERqc0hWUWFsOW5jS0Z3CncrNWZtTDVWTXhUUXhvU3ZodHNz
            Y1VLOHU0RWFiZ1RjS3h3cjI0bFRoczQKLS0tIGx2L1NUczIvVjA1NFlLSC9lYkhV
            bzFGWDVtZ21VdHp6TzR2bk5CWUhxcXcK3frvc83Vgk4nyQxmq163BQRohPqlREYX
            xpkyHu3KnBHEhbc8QoUILowCnvsxez8Iz9QdcGlrRxnTICG+kWuFpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:35:24Z"
    mac: ENC[AES256_GCM,data:0oa0IXqqlnUFDLwEYqnfVEWmZg0n3tVYfntYdjaVn51I8RjP+Y99IaTFFeApQzlwCPxmOsBMPTqVb42n2H9vBPUTkIrvMS3y1+J8ZzcZylbzqa75S7JzL/aF+RwwELJT4E/vnaTva0ibplyqqnySYS3YwmUTpmxSSLJdqMMZZqQ=,iv:9Nw0t71C64vU8J3BPrkEgOBX+ES/x79jpy1OxWUChf4=,tag:JKQsno+UVkW6RrD31g/AJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
