victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:z5745BMYMsy454GBpstg/S4a+mkniAQKmMw8zHE+erw=,iv:ZU9L9FBnCke5JNX06a1B5fJ6/NccUb/dCPaSvbgN4VE=,tag:gB9kVCGnDUfHDc9o5uCa1g==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:3J+THP12A6mTih2OSnkEHYZhdsc=,iv:0eo69jWepdg2Rj8fj7puvS876VyxJVuoHhOv9TtHf3s=,tag:TDHo9B5WEi+v2z9K9ppqZw==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:Lqp3kg==,iv:rkc00xLe9sl8HtEHJJE7F2QdVIvHRb4ntoq9Av3w/ac=,tag:ZNtD9ryfQmEcNOzNtY0myw==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:+sN9V/BCQrWR1tC+uLgedCQ9Yc/YWq2LwuUb,iv:pNKDu/ajjKb8RSXb0+cvkYownBncXKE30iZocSMpj1I=,tag:gb+Wr6hbC8p2cigkvL3ITg==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:uXj5Xw==,iv:VkQCmVcsFfsA7Z/zTZUW7CJJ8KGWllfvKXc36JnvuCY=,tag:eLeVYr6cII955FnjzWeBkQ==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:vdAQ9lJ4,iv:W95Tn6bls5ghv8mMm5e0qSdr6+VqeUsU4C1p13t57WE=,tag:NW9O6dKLmXWTArdevgcdQw==,type:str]
                default_theme: ENC[AES256_GCM,data:vnKg2+1Z,iv:py9opdZ4oVdDlQwnfG57eKbSwEkR3yCkAX2saZP5Xws=,tag:vAys6JO0doNtjImThDBNFA==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:Phx4Cg==,iv:efQSNIxd1g8v/q7uIZxRehZrtZqx5S332oLQM3qkMDg=,tag:1aDRPO7IH4Z/lloN1iHbIw==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:hu+toQ==,iv:iwwqvi2XVSOV2gT1MqYkV0TySdpZmMfKkJB+8cN1wNc=,tag:IVlZpzzJqmxsJvRALFKMyQ==,type:bool]
                auto_login: ENC[AES256_GCM,data:/jMvx2A=,iv:LRPAQMQe1b5wZxvRiVldxlqwJBbJy2X5cO0cefFKa1I=,tag:CZ5FgO/keOGDT0FJUPCogQ==,type:bool]
                name: ENC[AES256_GCM,data:zgYYsNM5fpIt,iv:6vA2hvdsZ6i5G6mDh+6SvPIMzn93uwe4n6k+8TTRSr0=,tag:JggZKS8HuLukV5QY0iFEtQ==,type:str]
                client_id: ENC[AES256_GCM,data:PHNaJn2ytx/kCJCn9MA4B8IKMXGC02/DXnVG3pyzrGUoGJE7,iv:1fd+DXa+CuhvfJcY+CkV3tH+JO6vAIQyB6ieCloiRZ4=,tag:hurozoQorMwCqI8q0fW92A==,type:str]
                client_secret: ENC[AES256_GCM,data:qepnjvN2ENq78UbTcqlPxQ==,iv:X0pNsB8tjVA2C1DaVdiPCY5XSFGYR+8axkjlaWk9740=,tag:LLfoGAGHru++LoZQ018PbA==,type:str]
                scopes: ENC[AES256_GCM,data:FGIEOgC3QY2h8PAf3RZ0P0aG75O7/KIJafn66TgyTQ0K/ao=,iv:AG1XPfsbd5cdodii4WMvPTxZrqF8XrWwSkq9Jf0ZLMA=,tag:kMv9Ycblp7PsfxxGLIBeQw==,type:str]
                auth_url: ENC[AES256_GCM,data:0t0DADBP5Skezqi8Lem6zoCmO7WNGrhjbv+SHG3zKHUBSUEb,iv:jUX2hzhB5n01dyNukGIxQ/+VkuC90EDUknxoV9GJ2ws=,tag:j+DTmdiFPIOuCqwrtoim7Q==,type:str]
                token_url: ENC[AES256_GCM,data:ln7krmzcBa8dNsgymJdAYZjRvaB16/15N4Ox/j4DKE8rM95yDZwg5K4=,iv:3AgqeafltdcTlktGYmjF4WSjq9lFrKhc7rWm3aeR07U=,tag:E1zp2Q47RvHw1aCyWvgmIA==,type:str]
                api_url: ENC[AES256_GCM,data:9VBfduDNeInQqbaoF+j2U6d+LNhndORp6TXoHKFaVr8iUHtqJemirSZDPxU=,iv:SfuD76YZRfRKe1Yuu7yEf7axiJ+JEivdMw1pIyLIqW8=,tag:3tUL3y9AVPMpVIy4ubAI9g==,type:str]
                use_pkce: ENC[AES256_GCM,data:ZozazQ==,iv:ctLFuP4Z8/5Ke/7iZzGz3FcUaTmqPlRMauEHbYwPO38=,tag:7Jx051xlt84m5bg+lDJPMg==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:HGVA2g==,iv:uwZz6ahNseQjQnQvCqhthBpmJRa+xwQu0kix7wfz+Ic=,tag:PVyv7Rhp7KltFc8ksb2ITw==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:rin3/ao=,iv:eHn81/gheDNhEviUn19MsfVGFBpo4CWn2umE9SFjhAc=,tag:tQRq0LVRXhZo1ICshxPHFA==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:p1US2h48gO4D63qc5Mj76qIA+bCHB+J+dGm1Rndb6CGoko8zr4/UMBHFuaH4OGw=,iv:AizKuWGbGydAK2oKH5Osth0b3YBf858l/OWhGYZ5muQ=,tag:o4lDCRwYciI7KKc9MmDpFQ==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:aPpXll1+BOr5yDwuZ/3xr486L5MwHmgIKN1qKU3OlGrKAqBGFS6PZoeQVzYCBoDCKNE4GwEupnHq7JQf0mMTiioTidpAJiCH67x/,iv:FcEpwDxI6/iqFTdOd4K7g0zBsn9x+sh0eSlyybeVDsA=,tag:e+DH2RHddzS6GdmsWwMF1w==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:gwucuQ==,iv:mqvvO+HllOYvNBPVbiV14Kst5jvLPG9dTRS7DVr4zCc=,tag:0KQDYWAnuUbu8dP+ypeKpg==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:iFRGjA==,iv:jWoI3MR5cCdI/glle6Bkv19GJAK1POm2ngJJ2NrtuAk=,tag:IqumONk/ufy35Yn0pfzJ7w==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:eZadXDWvreeoU6pY07M=,iv:yNzU7KRmCCbq/phjQkLfeX9B7D1ETy9LQz8zlUhnrpU=,tag:nhwd28du3cXXy0A2/+y09A==,type:str]
              targetLabel: ENC[AES256_GCM,data:rtGYITgM+oM=,iv:i8sgUBL7dYjdGVMav3/5VUZCMxogrTcXTiLo7rzQUW8=,tag:T0NutgqBSEAr9399mm5tBw==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:VDUCAtm7,iv:qzHcjLuu8+n76sFqLlN4J/HVWQsiLz5GXKLdWlZVWIw=,tag:W6kg6ds/JR4SZf4ywMoS3w==,type:str]
              auth:
                - ENC[AES256_GCM,data:04d+nIHhediVCLDQMg==,iv:w8EH3BCRZDd+couv5WgG5D9ZlCvzfDX8+MT+XCEu9tE=,tag:yMeZfx+zlX7ht7cXvLOhEQ==,type:str]
              name: ENC[AES256_GCM,data:Rgy1x9p1H3g=,iv:1YVSzX+RZ1zRJjeSaVA9M8ZeV9D7d4qtGUzBT8Uj56w=,tag:KSmdWqgcwzsMkLk4iYKsiw==,type:str]
              target: ENC[AES256_GCM,data:Dx52sg16lvW159GQUw==,iv:vDklweODAv4lfdPA/1JjN44joz1e9ebPgo9Avjn4L54=,tag:cBQnSZh9hV7tHNW0qLu4pQ==,type:str]
    config: ENC[AES256_GCM,data:nxPR1Vy2zMH3tXd3yExxtRwlScWb9yLkl84P1KZTdlVA2uTxnTvLLuB10cVjz/YPh4y7SNIvyogpMM31Xt5cWLbzd/gECSz4r9xHO/DDA2R83YHBRUrbNh+jzrhWukpFUlvmdqUP/Q6MfDiZzhOFXCOmjcrNb9Y4W1LxomhRuZFUly5Umkp1myCLso/1nC/y+KbegHOHsBhRSYlF2ThP2tEWG4TIa8s+mBaPJ2fPgxDxkhaGFaqJJw1tLluLYAOvh46F9xmhDaAk0d76J2oaw55aRmBf5WOrVReJFbzb7KJ1VCvqCSxdW6EBbtKAS2LSDXeSig==,iv:v5wXiGhYCvZf+LbYWFHoFoxKPH0GqIs0pS0CETVgw2g=,tag:83xB3IBsBDMJoZ7lZDIWlQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZWtQZmFhakdXU2tKNUsz
            cms4eFMvOWhqeXU2ZmxhSTFDS2dUcmI3QXdBCi9tcWRGNlBVZmgzTjlhNHIzbXV2
            bm9nQkNScThFc3lESFpXOEdEOHhEZ2sKLS0tIDZodzdEczJDczFoS2dwcFBEMkJR
            Ykh6aks4RldlMTYwR3NsamFZamdnQlEKZHjQMNfg3XWRz57VfoknAeJN86ChIBGx
            ewTTV5Xj81JwA/GVDBr21f52yTZ6mgJgxeGMON4HBef9iP0YrjJJUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:59:24Z"
    mac: ENC[AES256_GCM,data:Iu07rMxp0f3P2SsaHfhamTtyLUQ59pjDnAoeNu7JoCVmuPF2dsLws2z58QWre/Aq/pov8/RDBnuFBrBPKT7V+V076xKbDq9qZa+XqbKfYHhPMTsStqvp2m+Bz3Qb4ZxjYg7GHJM62gAZkP4/QxDTrUuwy2hVjiZrPGazNrJ1dMc=,iv:0p9MBnmN+60Vzqedrt2f1W4IFu1uLi/vkzjUJMmsCwg=,tag:PhwEDG66j5N5BCnXDmEAMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
