victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:CF3SCuI32qlmIRR8u1k9gO9FVO0vMoQEj7QTULer8wQ=,iv:/nMHpxMD1qShDW73iPQT4ijOOmGVjlPFlJZbuSThRsk=,tag:515V0Q2aTxy6V+/9HvPHSQ==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:DtYUcDnaF5YxMrnMGN9pyhqgUH0=,iv:y1ouombujOYniLvIz9Flyfr6UHKw3AeViTuRHDw5t9E=,tag:/liRaJHiaKIAGUvAr56S6Q==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:O6mWWg==,iv:M2P0P//uFEppZHzqZLbw71IXW2fXufr0+iWSA25bwu0=,tag:aLBQKrrEwugh5wymbzdvtw==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:0nxrJmWC3fiDi49NErWh8gMPKttQFMfy+jZN,iv:BnsTs7xAytZk1gK2C8mmB4ylTvwg2sFAnhpNgPCf138=,tag:zmuDYW79iaXeuNOoR4nKwg==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:T02ruA==,iv:v9+M9+dWUhb4/mSFqMp0AkV/tOK5iavan92pgc5AC1U=,tag:LycQg4Rnim5TT7Lx31G/2w==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:dwZ3xaa/,iv:Kp0cWcyxRNHv+DRyIQQzuiwv2ge5G+cH1zx0YOEgoH8=,tag:RjDFStbmesvsaQacBR2L+A==,type:str]
                default_theme: ENC[AES256_GCM,data:YggFjzNb,iv:nj+8hA7fRbktEbS5wRRziUkrFROaCSwS4ZcXAbjv6OE=,tag:Q1X5uCKZf6kuijHM8/nSXQ==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:uBTtXQ==,iv:eKPmrKuviQZ8eCDo/B4yGG/1UGojX4FdEpo/8NICrJU=,tag:HGYdNQ6eYA3Sg04Q+Rdd8g==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:4/SFDw==,iv:lNQ5RYxQr9cGTrfapUS36oxL70LeQkFPmQPAyEXGB0g=,tag:n6jYlfdDKxl4qorjENxoPw==,type:bool]
                auto_login: ENC[AES256_GCM,data:fxFGEm0=,iv:3vslSRD6HZSuGXIGJRyNkDsECq0Avj8LVjfVoGZNznQ=,tag:W4xUYBqy406+uin9xOPxyA==,type:bool]
                name: ENC[AES256_GCM,data:rf5tltpCh3Zw,iv:Z4dq0imCiaM8lgZEi56vuF8bG4Aqi41KX79WygPjIzU=,tag:E57halTmxA6WK9EFMe/MNg==,type:str]
                client_id: ENC[AES256_GCM,data:/QAwG7maOaLHwo8Bb+AjC3bScPn8aPqj6TICAzJM2HtmfPql,iv:4l+dbkokYZ4cd51E71FJk3GzjUyxoVJqdGa/hnG1Tt8=,tag:i/BFc39F+70FB64Cw7QsBg==,type:str]
                client_secret: ENC[AES256_GCM,data:ZJmr+X3rBMb46cE1iyej3Q==,iv:rwCEr8OvRqM0JM/2k//UkYtFCM7DIohfDHUptjpiGAg=,tag:D6/u1Oh5ugJHivf1XPz0bA==,type:str]
                scopes: ENC[AES256_GCM,data:5NZkxkFYXapPGlX9x03Bi0TsxYRgL22YEkEhJ8iP7JR74kE=,iv:fAnJc0BmXumUV1ZU4AMj23SiDmmshLcZZptu3+eskHs=,tag:fW/GoC8/j79OFb/MnCVFxA==,type:str]
                auth_url: ENC[AES256_GCM,data:YlPgclBQ4wfixUH8DP1FpIFfpVXm6mfGoDB97OPKB7dvxbPX,iv:8E61xHN6xTzqyyS7wcy6eltJ5/4NvUR1Z/6K8r2myPc=,tag:Vh+QdDPXww6sDWQgB5/u8A==,type:str]
                token_url: ENC[AES256_GCM,data:d4DQlz9vjdOYHLBr4Vr1VDY0SqqFdSD/FQ1fA62/sSZt2AnBI4TPBZ8=,iv:AVkUXGZzuEFYml1RCPpvJFlZAT6OGD4t7FweYwtwrc8=,tag:kriedkdDizg4J6CTNkLqXg==,type:str]
                api_url: ENC[AES256_GCM,data:k5VToMy/sxw3LO9VRbX5ASYBJTMsW9tV+te/NDT/aMfYVeqLeihksqfq14U=,iv:8FxyTiKDr0gTvyu0InqdwEEP8Fpkek6OUjCYHzoPHic=,tag:SonVT0Do1MumDs4np8AP8Q==,type:str]
                use_pkce: ENC[AES256_GCM,data:TufPLw==,iv:OiVptkUnwJVmN5Dgr11chg6wNK5gsc8PiW2hbuPVAeI=,tag:cvlw/89NZxLyrTIals3HAw==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:jffuUA==,iv:2Tjxoa/k7gwerva42wll8S35SWEbR40wT1PUjeYoUro=,tag:Lx/pY/ggsvtpiq7iA1ocLw==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:8QVtw5U=,iv:V2xTRcMhr0TcXP28iG6xN/PMePn1dLZLWUDHH6a/BdU=,tag:z+236YF0YgII/ngnS0++3A==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:2N2XjOG7vYlnyuboB3WfbO+7UNDtGmFA7oz+VsGTP9Zwo4vjsL2oSpEMncbm26I=,iv:6hzI9yrBdl2mNopRGdkHQJISLOkRouAPQxF/lsDbMM4=,tag:oZnftljKS6VOAsHmunKJsw==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:SsFwkZoxHY7JW7LhglmebD2sgfsT3YJ6OmPO3jKkbxsMkCCua0UxhsxVSzW8i3ceWEYhPH/QSi2jGWl76rZGJVF3K/XqpGObFaTM,iv:sdIk29JrAViXTlmFguYNR+rUcf5Tx7M86+isF6vsnPU=,tag:8Gv9CBw0oHdT0XtHnqfvVw==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:cYDhIQ==,iv:jt1hKQ+C8rO5OIc/NpueBnat8ed/mEKl7TEcoK0LmJE=,tag:qMkO3+PC6yBEKkIUpVeaag==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:CP9dAQ==,iv:Q6sloqgA8m4tztI/a0GK4Y0t4NAGpkiLFx41Nhhkqao=,tag:hW41cFiQwTHrO0nhs7IVlg==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:RVl/t+TsVbt5JMdvDh0=,iv:/Fa62qMbWEO8JJoOiM8kMRJuInaDIKPqy1KF+PMdAQI=,tag:iK/13U6fzUVbGweiQYDr7w==,type:str]
              targetLabel: ENC[AES256_GCM,data:755ZOBPlozo=,iv:fOvvVWgMe5kGxECUSByJ4eILkBYGaccleJfOisQVpQU=,tag:nHHF0nTHPBCvZc0u7dMOwQ==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:pd37XEJS,iv:PM42mMNhbeDkE3XQdCSq+3o/vKRSunNdDMpXr7A1Ueg=,tag:mVVbxF6q4+KXJoU68YjZwQ==,type:str]
              name: ENC[AES256_GCM,data:sqz4EhX7xF4=,iv:Uvr5/OPHXFFO4liCCftCy2gchg0IOnF74r1EctsQLAA=,tag:FlUwxsli+/UyfGMA3gmrPA==,type:str]
              target: ENC[AES256_GCM,data:HR5dyAtRNfhDAkIpAQ==,iv:XSvHo+ek1kr1heKoWdXTe9f/nWkQsXzYRizYJHrDpJA=,tag:nB3pYBpuSsnRRDklGmajaA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocnB0ZDcrZkVJeC9oSnRT
            WjVoRVlEZWx0RE9TS3dROWdCY0hBR2lqeUJBCkpqanZzOVlFQ1h5TDVhK3A3Mk42
            eVJ1WVA2aUtOVkNLVG1hUlZpTm5lSnMKLS0tIGN2bnVBRFRRZjM0ZURuQkY0eEJ5
            bVRRNlB2VUxhWSt3VjAxNGlwV3N1TEUKr5AZTZ1fOurlWLmjixDu+F1/3XgZtw4B
            zGkQNXX5X2iShay1G1ysEI5phYhfUSN+/Zf6dsK6Grj2b20nulGwAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:18:59Z"
    mac: ENC[AES256_GCM,data:65gFTBUFYH5aw/2TU2nA1MztPZmx8hL3qnveWD18dSKQ3L34Bdh+1+2VdKFFqvWBoJys7AzWXAhKnkFBij8f4zrmKc7BV+jxpr8jIYuYM8x8UhdR/qvJKSgVd9PTmGqEYOOzU09fITw3QQ1Hju3W7+tXp/M021N2v4q5LpsIAbE=,iv:Wp6OFd0+EjRKpdVEMhb2c2XZCPjMvpdxggmfwTkT09k=,tag:EkbiVr+qampAITzrALPn8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
