victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:hc0Yb841ERKuHUyvYopq+BxeSRbRULaJ1rnsEDamL3k=,iv:L+EZ6305992Mo5mAGGm7NhkUoscdJkauwivarpF4bqE=,tag:ddsrF+mHnWWYR//wf5QSNQ==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:osNlqTwoDyu/v/+esSRY9tXFTiM=,iv:HwyDLWclifvaSsFTtCpQPOPSpqszzl0cnDrYSq6xrfo=,tag:hINFNsYGQ9jqh7y0BDJDQg==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:rcOAyQ==,iv:zKLkkqKA1w3+IfHeIBRjADfEYl30E9cLsBRGezHOmwE=,tag:N9veBIvHhjWIfsLefljPyQ==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:/6sKQIC6ktxQUw87h5cIyE9u4TgHQJMKjM0k,iv:osSiXKf3zJpYm1ce5QlHD/l0SP0quDZlxtosRkNpLaA=,tag:N9eC4skoBossBXTs+5klXw==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:oDhfrw==,iv:zso9mmKxIWwSikRhV6i31kgJauWlAhpovE4ZuCoeECo=,tag:EfNYSPjwwhK7V0Rlunuk1A==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:FogMSq/4,iv:+RVGdGHHtvEA/RaGxCzhbzJjov/a/kaGPbj4qtRPvQ8=,tag:lbW3JhJ4mMw4iE8RA6kb3w==,type:str]
                default_theme: ENC[AES256_GCM,data:XU/cs41G,iv:wUKkwdZYNXqVYG3oX56xuCX6/n2/Njs7oDAX0KQGT1I=,tag:/wnLFYolDo5RlxbeEyGUUA==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:/kFzwA==,iv:W8cTjG66ImpLf0XZQd100kOtc0vL+g0eby0eFhJiOzo=,tag:RfcGsZSjACYLzHCCofTDCQ==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:+3ImRA==,iv:7BIWKmyHdMqHcUdFHIrX2nAVM/rMDmOK5LFce1VpAVI=,tag:d4OMEk6LlN0QwQ+ajxDjlQ==,type:bool]
                auto_login: ENC[AES256_GCM,data:pAOkuls=,iv:eKomZ8+VRDgiwvxvb7FBTPIGeocQE9PIwX9Cl+AFTIQ=,tag:kZxuE7ddAO+og+X58ML7Sw==,type:bool]
                name: ENC[AES256_GCM,data:VF1gMqulkhxx,iv:1g1bfkvfIOd99wnaDvQuxm9wbGYeR5q0lUbIcBKq48k=,tag:SX/8wkpWSE8nQeATeOrxzQ==,type:str]
                client_id: ENC[AES256_GCM,data:IVNfBvgkNUTk2XfLwlRCrZru8iWebuwbNyf2Knd/6PWvaqDZ,iv:QYKiIWPVkhkGkeQhI7BqHVldkAOpsop/+8HM6qNDSn4=,tag:WhDzQSWVPO+DYJMiI8z3kw==,type:str]
                client_secret: ENC[AES256_GCM,data:M6m0uFkBeh/MynjqgAUtyA==,iv:4WOMsfiowKCmQn7W/Jm9iMW9YO2zff+gOSRAtlZy6ME=,tag:375DRF6TRNdELAdaTn9P1g==,type:str]
                scopes: ENC[AES256_GCM,data:ZkXn9KOXptfj17r0aISHug6qFbZMsJw9/22C56GWlhjDY9w=,iv:Pgg7T5KkTrB4H8d9ymjrg0cG861Eh9Gutd5d7HyutWs=,tag:WGX/LgjnYuxCHqrsLG1zBw==,type:str]
                auth_url: ENC[AES256_GCM,data://bSn0K9lrGnfWNEM4YxxNwx3m7zjqPiPRs3KwG3xppKeDA+,iv:YYkaysbXT+C2FU6lCMm9siQ/mv//YmvvQvttPyv1g3A=,tag:l8dZRYpoE5h2/FKHw5aP3A==,type:str]
                token_url: ENC[AES256_GCM,data:9F39io0DwLUyihIm/H4nld+F0IWYzCSQejpRMi/nnvJaxgckxCeJCt4=,iv:UfC+5msMkcm/A0Sfc7ZwQBY+RgKgcq3b5ZH/mdLfnQY=,tag:sen1C3AFshsrArmnzqZ3ZA==,type:str]
                api_url: ENC[AES256_GCM,data:WWcC3Y/ZWo26IXQtKLkJz9rTy9kJKf90kPeOo1SeGVMjsR+uHP6J7zPBAcI=,iv:pVTtcxqxAwMNQ6cbHYRi0T8PG85EnLIrzim1KEVWmBc=,tag:yiKmjm5i2IJtWVNx6HU3yA==,type:str]
                use_pkce: ENC[AES256_GCM,data:ZHkDZQ==,iv:AxgJKAiladZCIsiR3Q0pTmVF2ub7s0OOtnhApEqbeYU=,tag:GZzpcQHGy2euUPJdmhBU5w==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:GsCIVQ==,iv:8dIo++iUJrIUWe4E/L1oGX+z773ZMxSK1P8sr9X5tUw=,tag:vml1+K7WOq319ASXP6x2tQ==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:dHNxy+Q=,iv:2AZ/rB1TtEs3+dpC3zhfpi006LGgK0wMTuQFupGuESc=,tag:+nqA4qmJTuQ7r3Aj0iREkQ==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:ldJEXJXJvCcn0gwrdKGb4IuMlW0NvnVNkhH8M77696l96mH8CFlFolpv3MkJFB0=,iv:znTyAnLsBV160P523N/4L5laT5ZuMIhSNV2ESuAK95o=,tag:GMi1ZQuyeAHAHaBc7JsnQQ==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:CQAKtAlXJU5wTziyxcMCVzWPfYlTU9CGhCDU4rDa2540EJJvGTsR/X5wnwYbM2EGXOlkAonV4wu0fo7R4anGJJ77ssc2rWZsJ/TE,iv:HMaV0nU61QZXNFmGifs9JdmWIGUHi99Cv2+GqyVUaPo=,tag:Zq9oQA8Txm+IPeNf+m4W0Q==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:5GKyag==,iv:ZtvATTLfCWpokpxvJp8c7QcbX7lIiUj59c30Ia5XkbI=,tag:zdcfzVgMuw2GK/r3USllTQ==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:Of/k8g==,iv:3gPrpcF0ex3PUBlQKja+N5T5a79rWMhaas2v0uoVfqM=,tag:t5vxbcuECR/f09Zbcz+7yw==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:S5Sh6lHUk0N4GmNBWQ0=,iv:sBjvhYwUJkceQ3jeiEUQj2rAfh9f7jGNHcZNiI5h4lA=,tag:Z+qZ9vFEymxOjfXekTyyTA==,type:str]
              targetLabel: ENC[AES256_GCM,data:UL6YF4np/9c=,iv:LRW1HHE4yhYmhjWwX4sWRhpQkjhNfmaqWeRofEz/0GQ=,tag:th7uM0InUOaXI+BiCwtL3A==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:xN46t4Pp,iv:0T+493B7ivGnnLk87lLWm8LSiyzPCl4YwwWkaPgKPDI=,tag:67isBl9+FQgPMra3HPHD2w==,type:str]
              auth:
                - ENC[AES256_GCM,data:wO2UHKLO48dOm2WjWQ==,iv:sSNnAfo+wmO311n9FdtM1wmzK8MqwKhGa1viwEFUQ0s=,tag:fYl6Xa0ymyC58eDM/t4KMw==,type:str]
              name: ENC[AES256_GCM,data:wNQUPcH4fh4=,iv:Hr0R00MTn5aGo68IpISQ/qMm49T5qZdzNZghb1oJMC4=,tag:0AWrY6wTQJS//6GbmVrhWQ==,type:str]
              target: ENC[AES256_GCM,data:HrQF/KZLTq42kKSJqQ==,iv:oC5FE6xgl9CWgRCMD7DYDvtapetaFIjEZwghSM2K5QA=,tag:r/RD2N47t5RFA22dm9iopA==,type:str]
    config: ENC[AES256_GCM,data:WY+BYa0B+5GD8pW3134oSpi9RbUvubI9Hg7nfEy3XpybprjeU3pweg9VFzRezTyRwMj4WMsj/ycMi6k/or9ZkEZKT76iLSkXWL0w1mgxo3LXA3hsehZtiZa09ulFEQhE5hOuj9wVoWC9o4t0yCfcBwXmPE6SyY3nj5Hh4/Ao9pZbds072RgesiBdd3VT01slAWUj8WOzHKAvbWRsyBM+jP3WROZji7AJa8QCREpYlwRptE3MTrEEg6jKGbp85umlyQvat+w/80dDi6M8hk07U26D36yTj5YiediQdW++yb9JNXjD1cm2TW0473TMvWBZheMYzo4q0I8J8/ZT/zmF2EZoMzleq05/s/LETC6R2TYSduOtmJ2THYPUc+OI9Uz0M0AEmc9QY2UxsAZN3Au72kqQzXdhL8PMW2cP+FTjfuo3GsY2+xg=,iv:gATLr6gdDvQkiw5fwxF2IhFB4JbOPqCJGZyDjd4nwtM=,tag:djblTKYAmA6TudA/FfA8Bg==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMWRYeHFXaXBWY3hhK0F4
            SEtmWUYrU2tEY0JKRG8xZHhPNW5MYVBlWGpnCkMzTnRNOFo0YWpsMHZqeTlzSjlU
            VFlyNjBZYlc3alNSajZBTnJQcENOQlUKLS0tIGxBcnlaUVBwU2hnT1l0bXRIWVFG
            MlBNbng5ZHNVY0hQZ0dMSzQxMm9yU1kK5ruziamoAAc2VKXpvTdaeWzFfLX31CyZ
            VNhUlstei9r1f/JHuULlekwEP6kwxzb5CoJOVLYd44X3ek+bMkb3tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T05:06:01Z"
    mac: ENC[AES256_GCM,data:CQSPi1oiAqhXIOtbLHa6YO+YWSQf/zUTJRTknUwjRLwhif5Ak3O2QZRmuGcXZHDf1kpeIvSpZ77JSjNXD2reLdCLULS9olQjsKJZ0X0xiLzluTb1qbhNd/tfjOLNf6gJS57rnnvaD0quWYmLqoqbhs+AyFITSnaqhRcfk57STdw=,iv:T3dIXPfbQDZ4UlxfmVIuxmyKnfMXIQR4eALibVs2Quk=,tag:WZOVrY3FIJjg+BfTzTxEkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
