victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:Ta6PwQLGPGqLVIHoPlmh1dPSaNimztBWiUjF5utNZ0s=,iv:JeeS3SCXmJibVDOXOh8Ax14YBklskQMohR2IYOzRw7c=,tag:1MqCe2CyWevfDndmey5VCg==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:/hR9OFlvZY0bx5ScN4hub3rra+A=,iv:h1KaW8ub8jcoWpUp8p0yfudd1kdQ2iANB/Z8F0FOWEk=,tag:jHQ7GLU3IGOsJQVz25UCOg==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:hzAAXw==,iv:cSeuxvRofLrwG4K+K0XB8iuouoyRuANsVlX2mSbR3cc=,tag:Sj81O/2DBU+GA5tdzk8yZA==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:xWdC2gdyvGLF563dzqDEhRI7G3XuoPqyei27,iv:U+3TJAB6LCTfOaBf/lUVHistdEsONu6nAHQ4z/keMXI=,tag:LzLVAdK3RkLpgrBmoytnsg==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:Fiewdg==,iv:OYad2iQNyT/RDY0LFBoNUMJOd8A7cJT7fY5GgQ2XiO4=,tag:me+SgfOv5iPFuLnXnX5p8g==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:kbzvej/p,iv:eGY1MMiRPmhcfnZGvhbbqH7a5CW1O8CIgGLWG/KaSOE=,tag:7GCX+MeeqrIcL93kfdjFqw==,type:str]
                default_theme: ENC[AES256_GCM,data:p3vsETQX,iv:1QHcncEDaYqN4A6prMVSRsAiFog8UEx/HcnFZUqsEjc=,tag:K6htLPH3u9HrE0NGQiE3jQ==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:IPfrgA==,iv:BTlu7NGGlxL7k9nFJdpNTnLZxdWfXfR4SijDHnNnwXI=,tag:Bp7GeiyFNxfojGmP8BuNlw==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:ObIYuw==,iv:z0nQQ7vkU7Swunp55SlEDg3kSB5pC76CCYwX2eHoS5Y=,tag:AG3Yh1IiYJGjE6pLr/jvNg==,type:bool]
                auto_login: ENC[AES256_GCM,data:+siTFSo=,iv:HHQ+YbErKDvOeS2UTwmanovSaGHS8JiKHyEUgW50cb8=,tag:Hhqrsr/YTg5ODdlqX1CYgw==,type:bool]
                name: ENC[AES256_GCM,data:UJEbTsIn/Agm,iv:+bM9axswBrHf3+xQqMWzx6B1S1A60z2B5IMvhRumUpI=,tag:8E0Ht24FSB5GpYKFmut0HQ==,type:str]
                client_id: ENC[AES256_GCM,data:Rjxh5nz4ODsX5ByHSaKRuD7hSIHyM/En1eqKP1icPY0dxku3,iv:UuVbh+yjALnRD8dEVG1xGVYn27J/X38kx0C2n7PmpxQ=,tag:4NdL8ffu3yCvStdUrU+kJQ==,type:str]
                client_secret: ENC[AES256_GCM,data:2PlmtH+CSUt9TrPTUi4nXA==,iv:12qa6iOdYm0peSzDon8FwtW/2uJBfBeOCRWGeWE8Xck=,tag:JLbAZW5dgvh9ocXfb+CFvQ==,type:str]
                scopes: ENC[AES256_GCM,data:XYOOdKsrjVZUKGrt1FQQ35Mb8phuo/xnx4hxVUxr9IfRNgA=,iv:t42uQmtcICGLgsduPPnayuhJZ5kL210vQOFqrwnzEk0=,tag:PqzlEXbctiaQNg8pPrfhYA==,type:str]
                auth_url: ENC[AES256_GCM,data:viCvHY3IZFz4K/fBK/9oWWgxSJf1xjwiVVUaDmVHcmmhddCL,iv:KxvNQQ1ZDJV4fgj0TeZSkN6yH5q8dfQv40PeOHcNGqc=,tag:JxKN0qMweYUNxS7O4X3ZzA==,type:str]
                token_url: ENC[AES256_GCM,data:rp23SI5cqWJTMv606ztZY6/AlhJki9aTfiq8LPdvQP7dUjGa5QhFAr0=,iv:zoNsPxpjyrvJPmOjUztGMcDOo1tuXn5/Doe77gHlcIU=,tag:JojvLjiXZGp+AdEE/HFo0w==,type:str]
                api_url: ENC[AES256_GCM,data:erKho9ozQPcWOsabefYIq6zUt+IMjgGgLIwjspYnJYO6JRL3Vj+gUy97SnY=,iv:jspJl+N4KVcGFijMLxK9AK4n9dOCQX+4QvJ2kSZ7X6Q=,tag:FSLLlI+D+eVctWpiywPbCg==,type:str]
                use_pkce: ENC[AES256_GCM,data:gQGEeg==,iv:OfWjCFon98mGzEEobi/a/yII+qrgSY+VUAE7aZYji/A=,tag:KYMu+wUyGOqR3tZLh2J+Nw==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:ms8P0w==,iv:HljGZvfMT38MTgC1Nc5xT9Iju+/WR5Ij62h9skqbKhY=,tag:/cjZzTvTLF6TFVKhn5hIKw==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:Ym+d8Vg=,iv:klbSBZAM/lSr4sTtxRuMIMCrNpmbsEslj9ZsMKdrOl0=,tag:o+ZdKFDYdmTRAN4vfDhaPQ==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:DgvdM09DyVm71OHtaO1UrD/TNTkNQk9ltY449qJ9+SlKKCTiqJD9sOQe/NpMip8=,iv:Z0LHbrLejIbG5RIuZo+jCLUkZQ1CKJtwqsBjzXhS0Sw=,tag:u7i5KPhPOaEeozI7W2W/zQ==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:aN13GKVYiLeTGTUkx7uxuHE9Mb9pjLSTIiwWG0sn2kjm5wQKko6GJvVJq0pkRm9JVTurT1YkF8YxZ+ZKpW7+DiXLvvc/FKsRI3T5,iv:1GY6/QygQvFSjQvuR+9R8gh5PdZ5clcRn5TW/JFU0Qc=,tag:TeJLStg0Qa0nKmLYhjbPbw==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:Q+zB/w==,iv:hjjviNZJ71cAXu0KrU1PI2qfvv28IcvFbJHq3TEoOHs=,tag:Dewfz6kjbbNsrgiAaFU6bQ==,type:bool]
prometheus-snmp-exporter:
    serviceMonitor:
        enabled: ENC[AES256_GCM,data:yy4eRg==,iv:eIrkISkN87ilFunPUwoHyZDpYzc2lGvdTFV+1TGyGes=,tag:mfCKcrw+dRXPTkU2T5jg7Q==,type:bool]
        relabelings:
            - sourceLabels:
                - ENC[AES256_GCM,data:tFQA8M3kO97PShMmaW0=,iv:j75M5xIZkEJ2Ume8qRhdqnotCt3MglZxL4rApjAKgKs=,tag:Gceeq4T0+i3V7t+cX/b/Hg==,type:str]
              targetLabel: ENC[AES256_GCM,data:NPolBhdomt0=,iv:Q79fDg1RR5jzukvOy6qsM51rVGqHQfT/7UTOpCpg38Y=,tag:XC5P0satxEv/qf17s2Bn3w==,type:str]
        params:
            - module:
                - ENC[AES256_GCM,data:1hCxMAkX,iv:wVSKul/1CvAtVYwapwNJ7i1I95QseekRh7kj9iXl2oI=,tag:MO1hsc0ZIIo5Zm4FT3unfA==,type:str]
              auth:
                - ENC[AES256_GCM,data:OZIF4CHQBbO/Ngi8cA==,iv:dHu4TKSteMDVOk84dWW74NxEd2xjUzHyG0G38/jqEQU=,tag:M19OsqHzu8NPceE1CW+Keg==,type:str]
              name: ENC[AES256_GCM,data:468Erk/xnQc=,iv:Z0J2a9uZK9foVxjckem/fStgJz3nqe0MPZLC4WPpiR4=,tag:4ZCzaHJubcMkRBqITGoe2Q==,type:str]
              target: ENC[AES256_GCM,data:8WwsyO+OS0AReFMuUA==,iv:7ggTiRf4iHZaFbfJoHTFhRCHHc/BjmTCWu0WWIEU7Ic=,tag:chTdX+kGL+4flQtIxYCJfA==,type:str]
    config: ENC[AES256_GCM,data:nDGMMdcKD46hfzEYFZco5hDnm3/6/UwUxEIAoyTlcyYYit5JVg9kMvSnck5Y+SNHVV12qyPM5huEUgDMvtgA/HXTns6xXuzA2D4lrDkUlaRDho499PjYaE3HJBDJUWsPr9D2/7Iw+UnTt6MYhyS7LQc5rRxOLpXsKdQNoen4x/KvlI6r7ckVAUcILKlxXFvdzXE+BzB8C5+NEAqLgsr7nA8/pTx4OwncEBGIGOWfcC+LC+Ym5yCCbqDU6MZBj5WSRxhpjsLZnIc03Q/GLoky2eLG5at92QJj22zDl4KSFF/qY0Cj50BDmyj3ogOIlnQ=,iv:3JtiH+dzjUOwB2kbtBay9QRWFcc2ZGudyq/lCh7mfXU=,tag:4PbMBrCqO+GeemSnPp28ow==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTkdLbUc0YUcyV09keFly
            RGJqcERlOEphYnBraytBalc5NWJBWGVnLzFFClUrbzRJbmtPaERDcktiTXE1ZXpS
            NjlqZmIyWUd3L096YjJjdmkwSXlmcWsKLS0tIFRsZlpRMGFEZkpEYmRYSFF1Yitm
            ZUpRRUlEK0d2dERscVpaQzVGbzFUNjAKrn/0WyyStchyNzVQKEPN8GFvNmKyF0n3
            9dEUpsjmgQBfImo9gmyk+hQl3KDXzMUMhnrslMTYVCxZll7rmqsJNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T05:02:53Z"
    mac: ENC[AES256_GCM,data:m95jK3mK+y1uk9vcEn0+1R7PzvO46ZLp7DlAPTe94aIhVVQs/fTtUqexfwD9cHcHv6NfRitWwbrjPvR09sAloI+sfoBgojZr7F0YJHC7QaYvm6CmCG5tLcxok6N9VN375HhrgAUB0TJ5elrP/SyXM3N+SJTbHmcwKdWQKrsGViQ=,iv:l/hnrmNUILMNGfr1jCaJUvGzF+mdN6BdJWSdzivvoYo=,tag:MGUw7tPeAc52HpUKMQc+tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
