---
app-template:
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          nameOverride: boxarr
          image:
            repository: ghcr.io/iongpt/boxarr
            tag: 1.5.3
          env:
            TZ: "America/Los_Angeles"
            BOXARR_URL_BASE: "boxarr.mdeleon.dev"

  service:
    main:
      controller: main
      ports:
        http:
          port: 8888

  ingress:
    boxarr:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/name: Boxarr
        gethomepage.dev/description: Automated box office tracking
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Servarr
        gethomepage.dev/icon: sh-boxarr.png
        gethomepage.dev/pod-selector: ""
        nginx.ingress.kubernetes.io/proxy-body-size: 24m
        gethomepage.dev/weight: "4"
      hosts:
        - host: &boxarr boxarr.mdeleon.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: boxarr-tls-cert
          hosts:
            - *boxarr
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 4Gi
      retain: false
      globalMounts:
        - path: /config