gitea:
    #ENC[AES256_GCM,data:QHAHs1ayow==,iv:AE3XRwD+X1Wc/2N3ShISTfgB7RmuWaCneRIP00TWtVM=,tag:TZOn+HLjBNax+gZtdea5QQ==,type:comment]
    gitea:
        admin:
            username: ENC[AES256_GCM,data:V+RkwQqc8Q==,iv:tgLX8o/E4GFEa6au40SyKU/TVl03TNsyi/1uG/5iaYk=,tag:H6kXxsSZy/A8Km/r0bIG7w==,type:str]
            password: ENC[AES256_GCM,data:E7cPEZwi40STxoFlkIPmPEFAO34FlJt2sfk=,iv:tMWLSm4muszV04YYc67JgcLybHpMxkv/mw2yWZHvRKY=,tag:QyjcQeQoXsFghDSEpvrClg==,type:str]
            email: ENC[AES256_GCM,data:/R46cCim3cRuPId9kSbRAe8=,iv:8EboP5I8UNVvU4/HR/kzm5JbAz8T3SQjkMEBJDq+MiI=,tag:0Lh6pCpmibwrNioaBn/NUA==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb2FHMTRxb21peko2S0s2
            VDlnZ0xlMXJHdXBlbFpxeUNuWE53WHRLaUFVCmxoSE5xZXBVTVh0T0lNNHNHUFhB
            OTFhc3RVdmp0bWZiUnUyaGsrRWs0OFkKLS0tIEpMcnVIS2d6N3pZY0ptQ0JvVy81
            ZVZZTHU3K0trNWRBRkswUWc4K0JZSUEKZiSYn9IW4xeTkBrjNQtVXxf0VYIaVGzF
            tkRLvdeax8MFqGM4PWLpO+/JmmoqIaLd1rbuYznbyXYEyhQni94Dww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T00:54:57Z"
    mac: ENC[AES256_GCM,data:qyV3QwIrps3GwXIoHJRmOPPCJwrulfqyA3SWrImHswwM3eH15BG0/skpc8T2LYZxdn7xujXtQTaKt6Id1ANZXry0G+VRmNfI6kVY3WnGtd24//8xxuyxlCnjD9E5aWGbIW88FFYs0RDNa5mrKTqtFrWFjL+5RMRUw5b266mzacc=,iv:YDL6fDpQtaqTwbyJ4teMPpr7GS8z+Put/QuwvMbwgzQ=,tag:D3wUZQNl0JK62fZJIBCd4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
