homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:CA9hhRJbWA==,iv:bp/hNbkyPHL+sZ6/fvQ5oSYKGlCazbkjNjKgWS6pLQo=,tag:XyoxXlLyDemG9GBnKB4RNg==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:z5jj,iv:5D7dr8McmV/cYFOyvKlQLvcjjsOzRlLGQVtRHl5huos=,tag:8vdS2T4Ar4XOvTd1VT9/LQ==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:T4RaJg==,iv:CfTozyY/gAJdyLfUu0bwBSlKK2lG9xfKS4/nf9EbSzA=,tag:JCEcVYevZEq3ZM6bK7kAAg==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:VTzylw==,iv:KGH9wk3G0V66jflmgmQFzHrwgCMNf/bb4nZbixMtIS4=,tag:9Ody/71TDDZCbJuPDMjZdw==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:Jg1ucg==,iv:W1T2TmqbBqBTmSP8HLTkQgM9k1GgImVwvsOve6Oz8mQ=,tag:Un9Vookz9AIOcltD0jjG0Q==,type:str]
                    style: ENC[AES256_GCM,data:RAkd,iv:CBtmRtfIPsKfjDJySdfO9JikpotNTqX2/81CZQoDv6s=,tag:Oh8mYd5UPQ1+PU+MR2R1OQ==,type:str]
                    columns: ENC[AES256_GCM,data:Gg==,iv:Pq2ogULUPH5ioidUsywMA4yBvHG5y9dBzvSvdLGdWBE=,tag:Hgne4MqVcQ8sCtJSp6bknQ==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:iW581Q==,iv:oPqWTYjZvtpyWOM0jsqa6PCgwm7iZnJNAnyZfLxy/SM=,tag:nsL/iFvPHiYAndDj9EKrqw==,type:str]
                    style: ENC[AES256_GCM,data:0jnM,iv:fSO72YZI6ZSiiiNErgzqWEXU6nSft4czQmC/AOrbUfw=,tag:6Nz9zzxqM39SfMTpDmlcWw==,type:str]
                    columns: ENC[AES256_GCM,data:tA==,iv:Ozk3MFawBjDyZAYTo3qjR6gn2WqlZPVxqZXvNKj+3DM=,tag:roN4maM/squcjAXyua+Rig==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:udsh3A==,iv:kV1gVpSA+4nWlhmvl+LHXbJ+rlWv7WNLY1U/C3TcTPU=,tag:etwJ7+WsNkC5IcAwdfoOCw==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:byQzSg==,iv:UYk8UCuLGC1vWzznQtyD+YXIkTxvSDdp58F2/L8hyww=,tag:TIbNzT4ZMJ+WOXWZS1G8iA==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:MLqORwA=,iv:vwbl1ft1gF0yXuisNrO93Z9sLWg8bqOLdcicuUxoH9I=,tag:whXuyBOF5ICkeHpZm4OS1g==,type:str]
                    style: ENC[AES256_GCM,data:aQpm,iv:/YHXoPVcZ/fLLkePDTEcxBfCSrTC1XPIjuy8Jib8VWs=,tag:qfqRa7d/9ihw1KuAzusanQ==,type:str]
                    columns: ENC[AES256_GCM,data:tA==,iv:9N8Z19QypNHVUJ9Ky44tny2to17KSDn4cE1vBNUhEyk=,tag:4N0oH5nTZXHJbrvDpBOOeg==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:ixdnXDc=,iv:+vQIAc47CbLKoNDaQzSkg4kTFIQz2b4VYOYd94FlW6U=,tag:Qh/OpsSBOMt1KNp6bDcObw==,type:str]
                    style: ENC[AES256_GCM,data:/tvU,iv:5Dlf6VlasTMTSDPuwoPG3U3uAKDoD0aZGcnwJ2f9W9w=,tag:1hcmOk12OaTKAz8zxxrEzQ==,type:str]
                    columns: ENC[AES256_GCM,data:KQ==,iv:Rqb8KCCWA++vuh54RmR58iB4VS1wBTFPf+N/hkd5aSk=,tag:tnKHMYOgf+bAP5Xwk3zhfQ==,type:int]
                - Games:
                    tab: ENC[AES256_GCM,data:wPToIsU=,iv:rag/Q+STDtJscZS5BqJv84IVEZJ4Wy3TPAsMsYqasgE=,tag:oxC5AjZ0seLiU7q1MaOipw==,type:str]
                - Unifi:
                    tab: ENC[AES256_GCM,data:5kANgrcGGA==,iv:b3hI3tvviYsWYEq2t0QuiA/jPBDA/lmpFiniDm9J2xk=,tag:hKapRfW8vS8ZiHliLdnYpA==,type:str]
                    style: ENC[AES256_GCM,data:61aN,iv:Q4X6tznJUYz5n4mrbwvi/U8nYuMYDqVfqtcuYDywnfM=,tag:2oaOqTsG4fAld5FaVU6UZg==,type:str]
                    columns: ENC[AES256_GCM,data:KQ==,iv:s+JA7FEWbqN///8JIEBwk9l37FWhQvUR2R2Dvpexx+c=,tag:h5Ty8uGzfvIK1HkoRfhpZg==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:6BGBdVJz2g==,iv:uHz4P5z46h0bPwjZ8HyV3EYn2YkzlN1QuRhNHpIe4Zg=,tag:TjYjxALOmfTANwMPstkzAg==,type:str]
                    style: ENC[AES256_GCM,data:iLaI,iv:S+3rPxB2/ge5Hihi33SDf7HP+UG3YxYSbp904yodYSg=,tag:kja2c1gRrmuaWNch0L3WRg==,type:str]
                    columns: ENC[AES256_GCM,data:ZA==,iv:B1TEkTRpLvrpPDh6JRdO7gEl0hgO/R0KUYYtrlb/7d8=,tag:MCWXntXypl24s1qh0AKEIA==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:TpINgdDl6w==,iv:at7Bo9TKg0GyhMf5VZ7bMPt/6Wiz02ztU4jw5jok3yQ=,tag:/ipZEJfVjFHOwhwA+K/RoA==,type:str]
                - UPS:
                    tab: ENC[AES256_GCM,data:YhZWPTsHHQ==,iv:Xy8caIHzlmSXTTT1byplbCR3nxRlm7dVPK1Xzas3J1E=,tag:V6bf8dljaNERGxBJS28QBg==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:ZuLTLJctOQ==,iv:3TwzVMG9SNbxrD8RXszlkaCyT7MGGs2lzRj4i7x6b4I=,tag:J8ujLoTV4Zn0WxOIRTlQcg==,type:str]
                    style: ENC[AES256_GCM,data:NNWA,iv:FRJp5Z36m6jwxmva9CENkfAl5wFOP2e/cwG08UQwDnc=,tag:1G6+OAiPskUSm2SBW50vqg==,type:str]
                    columns: ENC[AES256_GCM,data:xg==,iv:Ip0nwQgzRavXzlrEWhwqvqSIQKbs2OV/Ecl1Ff20RYQ=,tag:sYwbkXl0QriOFTwRzwdBmQ==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:zASr0/WwlQ==,iv:LFwiH+OTtUeph6+CgWeIpaqTRhmuobgG70b2t8VDmi0=,tag:EkHi9W0yLjqLfC6OgVTgVw==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:sLkTYUYkvw==,iv:wH21chhc97ETkuu7AgiUFvFxmNGkQFeIt15cMpq7/ug=,tag:xEJKYYWIFoEh4sQ+qO/0jw==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:+orsoB/TzA==,iv:Izy9BR7yGkh6jJvrxyN+Y+e/IrzhcThkxV8W1T6Xv3o=,tag:BQT4ta33A5OX5GkojbQz5g==,type:str]
                    style: ENC[AES256_GCM,data:OpZg,iv:2BNrWjcP9CZ0aJL4B/c/yBd6VXsPe+nAvd++cLHHC1E=,tag:+qs4LOEI3gRfXTugdDRPFg==,type:str]
                    columns: ENC[AES256_GCM,data:uw==,iv:hqzSyL+dIGjnXM3UC6lB2r4A6fbeEBoWv71NR3j7GDM=,tag:/3+A5VBXBvuz2GfCWE2dpg==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:vU8L/w==,iv:NnlN5BBGVwtkLZs1mQpEdLtaCYjgL34AbzLav4ahgMk=,tag:66yaldNVqoWk0ZINeZYDaw==,type:str]
                    style: ENC[AES256_GCM,data:q7Wg,iv:mub7mFyYMlFpkaHfmbK+K8Il9RlC/eko0a4EMqJCKIk=,tag:kLdOoAg+YryKQ0hPSm9U6Q==,type:str]
                    columns: ENC[AES256_GCM,data:bA==,iv:8PFcDLMcDb7Hhrj5GREAnXWyRkfrzGTOAuizv97ZXyc=,tag:VHDuy5YtdOMXk4eHWJOY1g==,type:int]
                - Git:
                    tab: ENC[AES256_GCM,data:b8OWrQ==,iv:gSUPFhn+I/NfsjdVqWnpWm9ogxj9OlfaxNOYrAv/cog=,tag:hNg+CMtJXNPbTY7LqJDBVg==,type:str]
                - Artifact Registry:
                    tab: ENC[AES256_GCM,data:+ezc3A==,iv:ikfiM5yx7r4lm1HH93ANH34cO04OS5MTfq8zSiia6k8=,tag:+lQxeuaeX3ajoQpIJjp9xA==,type:str]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:X6oWaQ==,iv:TA3ItpQxlHd95ak9rjAS+ax4C5dybfNEhxE0p4LQMAo=,tag:MDH6MIWbcKcEQvQCglRUUQ==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:CTXwaKQrWB5vOpAtOJ1MgWaZaQ==,iv:ZCBJmgXT+EY2VMc66uttL5bCFzPlkIRfBTRLVdjRoXQ=,tag:u0Yt1WhKPdYeEhBGpcTbfQ==,type:str]
                      href: ENC[AES256_GCM,data:OIEofPZfcBYsCA77wHbTiBVTv2pmEjec6CeZxYZAF3/AtQ==,iv:ySTZTYUIT/eROZE7Ud+8AgtfKUPDq4cbITS80NAZ8Cc=,tag:ZV4OFz30yYLxGaq8zfluuQ==,type:str]
                - Cloudflare Zero Trust:
                    - icon: ENC[AES256_GCM,data:o2pjG16HizC2gi23t6zRMtBWizhR1WvgHQ==,iv:K2JLvAsKJpz2YYfzwmFQO+ktqX60Wy22wCT4YiM2vig=,tag:jgl6Ls1OhJR/2rEbQGJ4vA==,type:str]
                      href: ENC[AES256_GCM,data:z9njcJAQFhG3G3cbymk0ATJUJL3NLKxz/xMNJNRNF4I=,iv:UQ7N5xOvBf89+t1408bJ5FgrXY2PXyuRAxSMnzXnmhY=,tag:J7x54BZKnhgwlzQOkXe+nA==,type:str]
                - Cloudflare:
                    - icon: ENC[AES256_GCM,data:0FAatNJcWc69iar65ltWXao=,iv:01McOfzb48Gy4H5Sfhfq19/XuIuZ2T80cH8Kt5lA9Ts=,tag:0cf9wS6Vi2Rcpi1qQ0T2BQ==,type:str]
                      href: ENC[AES256_GCM,data:9xBGyUPYdwfN8RRvrnTT7vCGK0xJno4Qesa28w==,iv:taSHVcAg5wO6v32gHGPxV+wcCwAAnRXlzsD3jlqYI50=,tag:KEX1CmujtboCAHfqWTJ7xw==,type:str]
                - Auth0 Dashboard:
                    - icon: ENC[AES256_GCM,data:FQZl2jQ9F/X6lLjP7j1LDyTl0D7odQheOaadxjatYqV0ucCLWRnhuwt5nRFT,iv:eDHeSE8mYZSwi+mpc8klo5t4k/gc1E2HKKPeZkzR1AU=,tag:DzeEkzrWi8D+lJX0WLw3ZA==,type:str]
                      href: ENC[AES256_GCM,data:UiwfPDwuKKJOKf45BLnKzYcAWhw/amwolQ04E9hZs3si39J8htb/K95O2SkvYw==,iv:Za0MrkyKP6ptbVx1GIO2DbJjEpvqMe14o0ZMhhbvjEs=,tag:WhvphkI02hBN+lPFy7zasg==,type:str]
                - Crowdsec:
                    - icon: ENC[AES256_GCM,data:3zwKcmC+zplQFmJZUMtF,iv:ns5L1LsM9OzfPW/rG6u7hSfV2Nmxdn/56FaZSYilqzk=,tag:pRreZ5SLpjcW+GpAQmWGzw==,type:str]
                      href: ENC[AES256_GCM,data:9QoFZjH4wn04Mf2/pK/s+wQY59Rl2IaObA==,iv:upuGoirCmv51xBU2mrjTQmJug5PL+r3GVTIxT0pYwkM=,tag:RSRZYX2CE7QKgt2hnMqPqQ==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:L2qvZjv7qn2A1eqin30Ri066lfe8qyta6fC6AEtedNGJUaLuLu01HgFYnLf53Q==,iv:nxHcbyFiXhCyE4K/I3viQ6mms5B4X9f3poRDTfaoWEc=,tag:r6onSDXi5LIvxHiidbRxSA==,type:str]
                      href: ENC[AES256_GCM,data:MjfcJxGswpkJmqHVKK1t1rSw2b9mYuIpa9CaN3qXi4HG5/g8sbr5isyU1gXF/KXK,iv:16InDuNrC92DaEDsGbkNHsC0ZZYqO8k1lBKMt/etLRE=,tag:ncr+nzpJ2ZXQXF7YvSS7Ow==,type:str]
                - OpenAI Usage:
                    - icon: ENC[AES256_GCM,data:Sznu/XFhm7JBwfvUX5Lq3uFtRQ==,iv:AiWHlOJsdlvBVaQQxBbCn1fPDc6LuMc0syquz0qt+MQ=,tag:HYAMnjW9HBURA5FDfBzd4Q==,type:str]
                      href: ENC[AES256_GCM,data:zVUGV69cTJPiX0tW55yeQ9/hF2DVlnJqOYmkmu7o20pA,iv:gPHabp/1OjWJsfLwVDpJHMrkWcfdfU6NdbZjlPsgTAc=,tag:mQ0Q2kPHpUGwfD9PEq7jpQ==,type:str]
                - Helm App Template:
                    - icon: ENC[AES256_GCM,data:aIfZbVIwQgEjUDJKEOwz1dw=,iv:QEvAKOGqZiGTrUuieoIqrCZq+MaGk5EZtQ6eWZ0Ay38=,tag:IjT2PnlJ5xC+WBwJ8x68MQ==,type:str]
                      href: ENC[AES256_GCM,data:PPXTLHQ7NDlp3y43jJBsHxk5c4HWZMsDPOfwNhtgK6JXjpFhNiG92MiibN6VdA==,iv:5IbA3WBDzhMpKgsdpevDkFpEjUOn2na+5rjnefSnS/M=,tag:cnqliJ5VKVemx01+BjPWNg==,type:str]
                - Selfh.st Icons:
                    - icon: ENC[AES256_GCM,data:ax6eQyZlOWUwynAOePtn,iv:LrP+3Q7QIn+B9QrT4NWKnsI3GGQfy3nQb1sbRZT3aBE=,tag:vhvnpFnoFYOeT+qrePE0gw==,type:str]
                      href: ENC[AES256_GCM,data:pxZw2v0KZrosM1wMpSDKn3RIEx6UMcY=,iv:KCTd0udqwszd6rS6kRbvdtnyazmsMmM/1dUjbtIjReg=,tag:ENGzlY+XjQTjN0NecG6mfw==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:yDCAu7/nPDbLmz+nWARJcvz6zX4=,iv:ifVihaiIRPRtC/iUqPTtlClrjBvy8sZBKSIgbOfa/ec=,tag:8POCQtqwr1aupL7+79PjoA==,type:str]
                    href: ENC[AES256_GCM,data:BKXRXB4SXb34XuvXY8TZmZ5Isn93xkc8GQCGmHmYHJ256G6OekCB8FPE1Zs=,iv:xvEsdvXabYhZHBsjFca5UgPNL/zLCaH2ESBskC7nE0o=,tag:Qpm468ccu/XWUrEBV4e6Ug==,type:str]
                    description: ENC[AES256_GCM,data:dUd9FrekaTumHrIMYeMz,iv:P5A5DOL5l4BVnLiQKCC7Zpm7cD3y2UPN26Qe+s2e8Dc=,tag:9OlvLcVKp7PtTNG0eHJW6Q==,type:str]
                - Unifi Protect:
                    icon: ENC[AES256_GCM,data:4SA1vtpm4Ky4d8nPZ44unR8=,iv:s8KNyaSiq1xHVCWpCesPPYvPETyraA8H/Qw+c8wTIGI=,tag:HLT96s0R6pSgsxyO13qcpA==,type:str]
                    href: ENC[AES256_GCM,data:DAtcq2DgtHxdY3lxeA5nbyC2Cys=,iv:5iUn7cYdOw47tkJcrpEh0/TW173NxDkJ70H0OiEb6EQ=,tag:nUKt/3SRQMze5AW3Y3IbKw==,type:str]
                    description: ENC[AES256_GCM,data:p4DfPti/cg==,iv:7v2SHnCwasm6rk4PvvSErvNf3hZElzEDY6PCIGMW8Ew=,tag:pGNmSECZuffTtQFiJWp8ig==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:8IJVomq1/PwvAbli5YQ0Hw==,iv:Ah30snW4Wue+kJjJtd0167OYo/Sku3/zmnYSPnGQ364=,tag:45MF04ud82M+MIVQIdMq4g==,type:str]
                    href: ENC[AES256_GCM,data:mmJrFTn0TadglEsej4DDkgH86gTqvvQVUw==,iv:v4cJaQ7+0F0Le9aR937Fvyyq9TW33XqG6ZWz65MrnIw=,tag:HFxrxjyMmiTtl7fL0FJwBw==,type:str]
                    description: ENC[AES256_GCM,data:GBN5,iv:ZwnTTZVrBFkaBMTiIjU3uoNsKTIiv3da/LMRnF6tiUQ=,tag:gXrPoztntGseieDwBMzopQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:gTGj3JHVKrbaBa5LZF8Rsx2jof/L9qA6XQ==,iv:QDiPAV9giCmeUy9JBGvNg9iYwJ5QU+7zJ8+XR5cRPP4=,tag:c0ihQVTB1EulUpIY74AL0Q==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:ynCTZ9owEOYpLpkqpQh/EztAyxq6PA==,iv:o1IqxWxQFWelrmS9epSrPhZWtN14sOMjvawPlKyRMfM=,tag:nzDZtqsVP9aENAYafp/jYw==,type:str]
                    href: ENC[AES256_GCM,data:aRLwu/zO+TFM5W2Kiq4NQbzYGXBHSHTB+VrJzDPlChw=,iv:IfHps2WzGLzJS1qB5F3tY1SQDXMbXnccfRVRHFMdSaM=,tag:iiRNTnauP+UYyzb1xnB2ZQ==,type:str]
                    description: ENC[AES256_GCM,data:rxmT4Bcp9A6OlGwuYU7U,iv:6hcLbag2P08+Z0M3rasesplHu0H4KzSkQfRXGLbZ1VU=,tag:joPU7lmoCA61w7WDW8nP+Q==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:K07KwWGK8g9M2JyERKs1Q5lPPSEPf8cx1+9MmKg10wo=,iv:uTFYVswt2Gtt6QZp6npejYJjK1lbNMSK+Y0vVBYbh40=,tag:m9S1sVLmgOvk3IPrv3raQQ==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:Mw1DszI6LgpDOjlWzy48XO+IlFuM,iv:aFgDpyk63+7caNuNjAMcBO/2QuBErhKxXtgViBey4GI=,tag:oRmrelRFm3+NBMJwVq2J2Q==,type:str]
                    href: ENC[AES256_GCM,data:dC62PSlZK96VAt/0Zq8qq6XLBEjuRAGkITY1GTbgxw==,iv:mHNRl3cJpsbQ97w5zfd13hIpjzj4KjVNk8Zy9Z1KByY=,tag:wRQvRi0vgN+KGLnQKnstaA==,type:str]
                    description: ENC[AES256_GCM,data:Ps+L0iZ4Z6UP8w==,iv:ebqR6pLaR07umUAOdwVl1jDiJcWN/nOvsOpjJIjU/dk=,tag:9a8PP4ouLD2uUYYqqJPz2w==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:SkdX1VumamClXNWd1CKXZGoHXmCe5OZop9+eL5fOew==,iv:LE6I8XqTx69UOQC65e+0X1mS1I2M7n8FHaqwEv7hbJk=,tag:rgt2Y0PMaxEa9rJvFmGI0g==,type:str]
            - UPS:
                - APC Smart-UPS 750VA:
                    icon: ENC[AES256_GCM,data:ZVh4hksgu9LnHQ==,iv:JxC6QqGp7qr63m/PamxlU9wGzh39RLRazVrvoYaNy14=,tag:5PB8UdCTRcKkVzv1ljPY9g==,type:str]
                    href: ENC[AES256_GCM,data:fFb+mNL7XPkPaLV64bKEKLrO9S1k+1NTlzpnSw==,iv:G46gACBnij67PHVqNfbjeGxWg2rRuuXpON2GINc5XT4=,tag:KzlrNlHt4VprO+1Oqj13/Q==,type:str]
                    description: ENC[AES256_GCM,data:nUPn5feGelrf3+CNfQZynA==,iv:uM1OyoVSorzRGC2R0A7TYYFH+XOGbCjQmsFc62p26tc=,tag:82NxDLiFqSD6FzSM4p0xvQ==,type:str]
            - Smart Home:
                - Home Assistant:
                    icon: ENC[AES256_GCM,data:n34GRGRvDmcKG2dZKlnOlQt3qBPM,iv:0pxpB7NYARENMk4DGNt1keJ3hMt7DRIJ/7s7LOX6vaI=,tag:LM0bVCzW/KDcrVpDYQxLuw==,type:str]
                    href: ENC[AES256_GCM,data:e5C4pgQVP4/++AmZdxXi7/T0L47YAifIi+7MQntjiEA=,iv:rrbDxWcA/f7yhC+roPKoXq0IzmZ5hzW2flSv7FEqvYI=,tag:6mLElG6hQEH1XmjDvJo1yw==,type:str]
                    description: ENC[AES256_GCM,data:vQpOQcuff5I57Y3vi1c=,iv:aZDexMayyfuCWmZ4I5bc+Snem+1oVxUYL2si6ofDSr4=,tag:ZAgPgZ7m7E+wRYCrdkTe1A==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:26aW,iv:yzFRdErN5A+1ZyDevvnNbKAWp+GtA+vvOZhibIbnvyk=,tag:ztpQn1IukDPEBcgdANCOVA==,type:str]
                text: ENC[AES256_GCM,data:vVGlh1BpG1Y=,iv:It4O7iPFBrHNpY0ptifaKxixDY4hJ24sTnEob31Vrlc=,tag:79B8ErLg1zYpipMQW41n0w==,type:str]
            - ENC[AES256_GCM,data:Fl7JKv0koCQyGjbT5+qoYdTBXmWC+wy7RvIyTtWPPwyo2Jgy7WMfANjwEHsgxRXTMPpqybBmHuP/mc2WuApWV+3ikVaf7gXfi2o=,iv:3j0wnqsHvM4iCrdIgfE3qmfIC4+jDmxiAKv0/7m0Si4=,tag:s5FqloJB9HDIvViMgaR6Tw==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:ONPJSQ==,iv:ydIeGMJoyhntXupfplS8EHBj9AS+hHWWfLrgypDJqaE=,tag:aP6OtnNqQFQhzcaY1+dQNw==,type:bool]
                    cpu: ENC[AES256_GCM,data:0VxDHw==,iv:YurkfgJHCpyKEfd1ucMrtkMD9iLupo74R8Ra1Wr4Y1E=,tag:t/1ShaaalH8g++u5AyaZSg==,type:bool]
                    memory: ENC[AES256_GCM,data:/Beqmw==,iv:9MWpC8U9Bf9JuCxTTyXGvbcnt73Uy9DhyFiYKzjF5bA=,tag:0F/YAwHxGF36Arttlt2u5A==,type:bool]
                    showLabel: ENC[AES256_GCM,data:JZtPRw==,iv:AhgoX137AESVilK85jSiD14JM78ANRIQHSPGZlba/7o=,tag:Lz+GuiaaCOcmYbdn8duZBg==,type:bool]
                    label: ENC[AES256_GCM,data:9REYhOezcQ==,iv:69yLGtpEThlLYKmiNT3FQPJFNWFCFhAoh9w/0IgIjms=,tag:L6iP4cGuh1BT31ba+ICgxA==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:XI0E7g==,iv:rtTK89wVqTSOqOmeN/FoSqeCBoL1KlKNrj/0fs2zkkY=,tag:17mset677DbVysAjaRsPfA==,type:bool]
                    cpu: ENC[AES256_GCM,data:kYkXcg==,iv:UX8a52APB95Eiit5A9/Zh9TL+MxNqAlFYnJMBAoT0cI=,tag:CNYFJ4fWGC4EHaSPTQZ6Tg==,type:bool]
                    memory: ENC[AES256_GCM,data:mr2AKQ==,iv:dMKNzn6TzGy7inNx4cwgxhiZuuZZlfToK/30/rH8+E8=,tag:vfGJ0joPaLLIRduZdokJLg==,type:bool]
                    showLabel: ENC[AES256_GCM,data:3Pt/fQ==,iv:A3F7eCCOgm07CJYgfl8pKqr+ygWlBlMFQRqbHOQixmc=,tag:lt6i4zkCcCZY4p//9/M+zQ==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:rOU=,iv:sTxFC5lgz9Boa43S3QtwjEHEg1oLnM0twy20vQo01/o=,tag:EsR2NONOLyRB5SSOohL8vQ==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:YCpOsIs=,iv:9qFtRduB5uYuQX84osQ2KBRVf8kq0QYgYcPzU3J44Cc=,tag:Jgats9U1J9CXZ6MMN9/SZw==,type:str]
                    hour12: ENC[AES256_GCM,data:kRBBDw==,iv:AdVLiSx3KFg4ndN3uMYcGYsWB1cuoqQFXaHNBrOFyzk=,tag:9uduDYP+5hExgYRe79ysAw==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:3xc=,iv:bGqz8o97KFPI/clwWZQJUhNZo220Z7DTSC5XqRly0G0=,tag:NWTy+aBNhPW+59YafSwfbQ==,type:str]
                units: ENC[AES256_GCM,data:bPtAztwZtHo=,iv:Dqwk+JPefYKsK0U5N2/p6lno6zYmFMds/Frgg/Gs6SE=,tag:0DOvYK6k0AUdM/dyO5jIRg==,type:str]
                cache: ENC[AES256_GCM,data:Vus=,iv:pRR5RRE5ZhGJm7qo4CzisIgRAfO6JEed/Te8AtVcrTI=,tag:+3V0MCjpBndNGNjtT4V2nA==,type:int]
                latitude: ENC[AES256_GCM,data:pcpi+VlMF0zt,iv:rSKsLYpHlFaT10jL3ZemCwItH/6aErrT43fVcG7vaSc=,tag:Ii/qDtVBLf3FtyiYUQYleQ==,type:float]
                longitude: ENC[AES256_GCM,data:IUUIigUVFAn/bV8=,iv:u0GLn5MYu0lcNnjmYLf+ox5SGd8HVizwhCwOQaBTbFM=,tag:GBvsM9J+nZ5+NdVzbIIwCQ==,type:float]
                timezone: ENC[AES256_GCM,data:CRTVCM1zZUwHNwhSmDuUBzoTmQ==,iv:qANV9ngjFZg0/B/LM/r5tbJo7G56iYLzcp02QB5G3To=,tag:1vo+ezdgWaR/yVWw6rSK/A==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT2FkZHkzSnJvOFQ4czRJ
            NnRXczVPSFFWVWd0UDhEL0dwb0RHVk03TWpVCjVCeEV3aEdQWm5KcGYwV3pLeHhl
            Tk1jaCs0T09WdVBYWGpiUFNVVXl3RjAKLS0tIG41SHlHcWZpbWpQVkd2Q1AzZDNu
            MWIyUmpMQU1SOFdsOEtNTFdhMnJOOEUKL/oTW1zzIW+TnnGy5WipoUNDj6EhYAxp
            5gzJw1qDBc01vNs+c2zneewrQyZ8XWTuBM7ZRAvvXjCz8Ae73q/xCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:08:42Z"
    mac: ENC[AES256_GCM,data:ihqd1iCzRIm5I8/IK6wbZVCDlmbPJzDgI/4jah+JZ1avoAPEwPcg3GyaJGjZHMX/nO9oj4uK9ekIVZPgemi+pk32xZPNmYNjwM5WvEZbbLZ8EjA4NfL7yEFk2nUoPDHoQAfu7r6hKDhoQn5Ghyqo0Nnwo3DWoHiaTOqI4c6WxrA=,iv:h8E28BUEN7TsXE8LQ2dXq7BykdSMOY4Jw13ic4pgDWE=,tag:EtHp5kj0QdjMZJlXKXcCEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
