homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:FzNPwjr/EA==,iv:Gl5pfnGVZX+NOT9dP/cUhvE4SaaWWt7vkFAQ8Yq8mJI=,tag:vnqeI0E/M75GYsvepfgjGQ==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:Bdtb,iv:7gzq+uOAc+J6G6Ek8dS6sMd8n9mH7RGTBzkUSr7sxS0=,tag:hzl0siQbxK/DdMcQQfihBQ==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:oienhg==,iv:+9YhVr6w9ImjRTw6AJu5voFC8IO4BtgSyTG8+uIPvUg=,tag:exPsaoGeD3ni7JkH63o5Eg==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:URYb+g==,iv:PtYO/vNQzPYLBQ1LmBuqNclQsPd/iTeUefKlvQklNsg=,tag:h+8A7zfmypO8HTRRjIMmUw==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:9mxA+g==,iv:BglUGQ20eaV1DvuD43nwjVSluMrjexRnIkbiO766Sn4=,tag:wqk/8aFT2uV7ajPZ6fqyXw==,type:str]
                    style: ENC[AES256_GCM,data:jmzv,iv:K5yTp3dGMlQrV40Q9/E5XaTaF3pPjo5LzPitwUPb9X8=,tag:bCiON5eINNNSLOnhgrCBMA==,type:str]
                    columns: ENC[AES256_GCM,data:IQ==,iv:W38HfQ3Vnk6HY8AB1h09LF40kgnfnEKw+66M++x5T+0=,tag:ff+Xe/O9nX3IYACZo7DF4A==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:FwhR5w==,iv:n2PhlPhblOsuRxv4o+86IXjTozZeCCgT4rBYjGO18Z4=,tag:yhC4p8YvFaxQ23zaYOP3MQ==,type:str]
                    style: ENC[AES256_GCM,data:nbz3,iv:Kf4xrK/opIN5Wtxbru7xu/Qn9+T3Tb98hIoXGXl5vfA=,tag:xEwvdx0M69C1ON2dPgHMaA==,type:str]
                    columns: ENC[AES256_GCM,data:xg==,iv:0a+tTV8YKT9QjihiU8vPJYOQuXkyjQAqDd1iaeynbQg=,tag:AWl/AByV2ljObhRa8NBgKw==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:1Xeurw==,iv:YfzT/nM9IXV5zlcAktKdxkKMcMz9pxkDBEHx7Td4p+o=,tag:kJqkOoVfhdnhTSeur/89hg==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:OJXGeQ==,iv:Gg6Z+5CssCOfYHD70/JzbJ+RU7pzffNBAP+YH8QfdEg=,tag:qZcT4hYbTqzmUYPkiLaz7w==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:uuxIjbs=,iv:teh/seHra0eBzPpWbdkBFKIQabGvn2dAiowDT6WjajA=,tag:E8+dPy9vsP6v+X+lzp2NhQ==,type:str]
                    style: ENC[AES256_GCM,data:M7rW,iv:34eOn8HfSL3bG2offGH7BtEQEqc07snn+WBwtUtePXY=,tag:RawpKpOW8mR1hDhlYLtmmw==,type:str]
                    columns: ENC[AES256_GCM,data:hw==,iv:ngDuT4yOGuX/ctqy2uvSLmHZ2E3DIYKYbz+1kE0RF5Q=,tag:oNf3AZcqEKCGemtvgCwb2Q==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:gY+S+xA=,iv:UdiB5+RrnveIwTGpFgKuxTL1jnIy8iMnlrYi3VjEFkI=,tag:a4qF4esKYyGdZpmfnStIkg==,type:str]
                    style: ENC[AES256_GCM,data:qx+A,iv:C+ErvbvDYK2sMiIpMc6Ym7lCTFRjDd7+Nt/N8HjNU+4=,tag:xypC2S7klQ63GEHLTZ/tuw==,type:str]
                    columns: ENC[AES256_GCM,data:+A==,iv:KyivzW+e8iQvaREocBbpOTQoZrTFyplMDUAbf8OLLv0=,tag:n1NmLVbz072Z+wT3RPwtKw==,type:int]
                - Games:
                    tab: ENC[AES256_GCM,data:/9BZq4g=,iv:jjKgWRCMD1jIMiYREukyQZ4rYV01nIOSNAYYmiPBtHE=,tag:Tm9z2Ku09Vm1yFznPJHUTA==,type:str]
                - Unifi:
                    tab: ENC[AES256_GCM,data:yRJLurIXFg==,iv:zZmSaRK/GtW3lpq551OiqSn5cXvZZZpuG3izcuIkZIk=,tag:PVeDkboAlhcQiRSheDy9Mg==,type:str]
                    style: ENC[AES256_GCM,data:DCkc,iv:LGpQFFJ/+78RZ598ghUhT3T1KB5Ha5HGPznEExrC2Ic=,tag:tT3+mPIwH9E8V4m3NzVMtA==,type:str]
                    columns: ENC[AES256_GCM,data:Bw==,iv:PVVV4zAgnUajZjZtHRPDSVpIOBm0q45Vq2CDsJVvWFY=,tag:YhzeBkr+VszKRB7sBEc5ew==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:Q3GO9pKiCw==,iv:YgV6T0BfNasgbWOuXPTZFUJTvAsF2zyTJrgf7PmT+1c=,tag:xv2eW2lcUBbW6N0RI56Dvw==,type:str]
                    style: ENC[AES256_GCM,data:pHl1,iv:d6YkzcGonlOi/SkWeDgA9+yGSehvsgLaW767qXAGh6s=,tag:G6hOOZU03QKnINm+7CRyLA==,type:str]
                    columns: ENC[AES256_GCM,data:Lg==,iv:02GYkGXtK0BNqlEirGPln1ZKHqjEU0oabPoNTULiicw=,tag:bWyVgWVYfbWZ5zBneuckqw==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:OxbCQDlgWA==,iv:Rtt6tD+Cq/VntL+Lq2xDFoZVEGQbIK5hDRniUka2A5k=,tag:suIZdpe4eLKLfbsDBv0Gig==,type:str]
                - UPS:
                    tab: ENC[AES256_GCM,data:rcLv9fg9pw==,iv:IHi0lo/zdxFRD5VSkEf6Ko0sHIB/qTp+XkNCVwUpHPI=,tag:bcU7rEQXJmZMwyueywc+1w==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:goPqzIgDUw==,iv:6jX/SBXzeYGGAN7caLlV/zdFEWeE/ZDBebN32qw7u0E=,tag:4SHwgcZ0TedDpn34ykArpw==,type:str]
                    style: ENC[AES256_GCM,data:7pvX,iv:lJsQnmiOQ+wQ2TPgdOeGXWFoTzlWJC/piGeSMbvDLz0=,tag:T7z7QbKXHri5dFShbSPXkg==,type:str]
                    columns: ENC[AES256_GCM,data:PQ==,iv:njK/O1rA2Ox2MLPzqLRYhoZDQdMyFC/PBt1RHKR61fg=,tag:eSDe6ljueczTDl53ul8hNg==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:3ICRA8DnXA==,iv:S4b6+32gW97ZAjgely/6pHdd9E1/o794gvnQlLS6lKg=,tag:rP+/lCxocJ9t+aegwtkJJw==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:5OP5C54iaA==,iv:2kjuWGjjGL22Qm3c3F7J7Oh6Zdd88IFkm4mjq9dfsCw=,tag:mEOWtS3qHKD4EwIkDdjSDw==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:fHvtq/ProQ==,iv:EfRhZAL8RyJH8OCOCsEe/0qOxAsdRREE3iqLCCWw418=,tag:VBQAVnnr6o8XDV1kvlhgBQ==,type:str]
                    style: ENC[AES256_GCM,data:kGJp,iv:sUQcjCqZDB0M680lnwljPyocFDZZgZm0kKg6cywMUBk=,tag:JrhtOcHpmfFt3I3HXZabiQ==,type:str]
                    columns: ENC[AES256_GCM,data:qg==,iv:PHZFFcGC9UmRxLtmePrqx9jeaSsJlCGF4D+iJchxB+M=,tag:AKJfdZ75Pq1pQiRPVA8+aA==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:Fbz2lQ==,iv:K0ExRv8R452nWOA06VOu0XjvF/EVoirRf2mW6azR5RY=,tag:nRK26KrcDa6JycpZxToivQ==,type:str]
                    style: ENC[AES256_GCM,data:ANuZ,iv:03wyK6sWuCG1ufdzTrNwE4/JcWfWn2+slHVlBS84Z+g=,tag:BZ3Aq/1BLnTkpQZ6d5ZgQg==,type:str]
                    columns: ENC[AES256_GCM,data:qg==,iv:iJ9rM7kPn0Vxy1C++cyAiMQS3WYrg7wZkUveBTnfTlg=,tag:xhq/+udVfKv7rr6lqukpgA==,type:int]
                - Git:
                    tab: ENC[AES256_GCM,data:2U3+ZQ==,iv:hxZwm728aPGSi14scTWIqZDbQbqYFSW2o8Sd/5WwsUU=,tag:Z1Cpani58gegmRtW1rJTwA==,type:str]
                - Artifact Registry:
                    tab: ENC[AES256_GCM,data:diuNvQ==,iv:XtwDyi6XIK04hhxsWA6gUl/RxNAgm2JOTAwqLgcHr5s=,tag:Ffwcnzlq2rVw3ZzX+j/MiQ==,type:str]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:JILw+g==,iv:rNEU+AJZPSgLjQEdbZMYq4fbKXnQ1BkYr2qOo7YS5hs=,tag:lfKeYD5Ibf8V6Oux73RjnQ==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:Jle78hrqpJ/tOhIC+8+3JAp6DQ==,iv:r8Lwpypq+x6J5G/f7X6+fCfbvnRas2eWD1ad2Vkrbtw=,tag:sVRtwnOxC0keLo3dCvtAMw==,type:str]
                      href: ENC[AES256_GCM,data:ctkqtiMXC46lHA5rKOpe4UtoyfByn5s3PQXa/pxaFbGmUA==,iv:iG672L9gtAraCREo7qP1bpfEixeLo9XDtsxDteqmEPE=,tag:XNKUAFZmt/UmHXp9lYib9w==,type:str]
                - Cloudflare Zero Trust:
                    - icon: ENC[AES256_GCM,data:DjKIy4jjv8WB65DaMBhHhH2i2Nj0B7js3A==,iv:PJR+DdBwQJSoOfviQtIqjv/VgTI+T1QAGygZZJNMym0=,tag:XN7Sma5a1RZosUTMeR3HWQ==,type:str]
                      href: ENC[AES256_GCM,data:yVkUxeeOacx4JA/DJ6PtFRl/CS7mdKdgYo0+MlWtaYA=,iv:0jzQ+vnCh17PpSSFxB+GD8a3PgM4fUlzX4IN6CZPBGY=,tag:65wl2/P/yddZBclWuXDIvg==,type:str]
                - Cloudflare:
                    - icon: ENC[AES256_GCM,data:oNV253e1EDLQlHLK+uVkHrQ=,iv:0Wp+ZEKPxY99xdIt19iju2uCGKbyWsFPMJiVmceNDcY=,tag:GzB4Sghumc7Q3wPZpfo5Ug==,type:str]
                      href: ENC[AES256_GCM,data:twGuBWRckpLvNYoL5HIN+D8O7BJbGOkI5a91yA==,iv:3KaVKoZHn/0W90FptqTbnpwpLqgNp052gY9KJh35kJk=,tag:t6p0K5lW1mxQnZ3uxXuzzw==,type:str]
                - Auth0 Dashboard:
                    - icon: ENC[AES256_GCM,data:ckDVdnBSS+QTpqzWXj+vYNcA+sf+S3xoeQAqUjTkA+BwXTpGV40ehFrCofHE,iv:Un0SXbdVAcmTPlq8iKaMDci4Oeg0N2s4gazMiFJYMNU=,tag:1l9hjgriYMplgCM9RnEz1A==,type:str]
                      href: ENC[AES256_GCM,data:uZt7T1miKS+jV8WuTnd2BzuhXeR3uqKky6X9ikK8Scc0zURVji/MXBfFWANkoA==,iv:ZefuEBROLFgLHlm5D9ntjUKHZCVeMJmMHzm7PZiDq2s=,tag:HpcRxo/B4nBrfZo578ikug==,type:str]
                - Crowdsec:
                    - icon: ENC[AES256_GCM,data:r5LIKUUeHgK32gcx8a9v,iv://F/dV2IETM1S/2W78otjLS7bp99B6tw/2XtgB1ckq8=,tag:OeVW2L/Y7OFUKGTovLe6lw==,type:str]
                      href: ENC[AES256_GCM,data:qu8w9oB1LT9BzrwXuRKAYokq+S1zqjCOKw==,iv:GNt5YAj/oKo0VqBZhQY68LmyRqeY8jWDM5F/HbdSDxM=,tag:Y8Dv47WRQW8EfCaBVJsjhQ==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:1a+spfM3QmW2+zioIxwcJVB6X4sQ24n9tgyOzz+gib81xmg7WcPA+pHSxz3EMA==,iv:cf0I4ZX1+ke2dpvOxyTLQ8KmPG4uFZnfrAfY75YS6fo=,tag:+ztoysyfReNZf3emeu1f6g==,type:str]
                      href: ENC[AES256_GCM,data:k8eBep9V4lzYBbgHS1RwE9iN7NbG8E4xllldbAFfQiTXdSneMgimPDJKZ4K/s2EJ,iv:9HxnkOsF+kUkhaE99vYzFFUoAUA3PmUMYoFQhIr/fkU=,tag:v6sQdT6aYC4cTX3UqHS/rw==,type:str]
                - OpenAI Usage:
                    - icon: ENC[AES256_GCM,data:c140rY/0NOKmC3F5yCQl0B03aw==,iv:geRNe5t4c0mTLwjE5kedI9PmZ4cUrkNu2HEbBNMr2aY=,tag:0pGyc2hCb4rUKX9CVYp89Q==,type:str]
                      href: ENC[AES256_GCM,data:Yz9aiL6HERqSSJf7ZtvT0vSbn679as4kEV4lX+UckO00,iv:mfshkCb4sA6tz8p6KntDWf5F5a1tueO3by7m3oAxx28=,tag:p/NPZFh6HWTs6RQUS15HwA==,type:str]
                - Helm App Template:
                    - icon: ENC[AES256_GCM,data:hjIeea8sOlq9sm520PoKu+g=,iv:WwPuv7CfToi+XtRYHPLYc6vMOlt6mRDo45OFInqUFBk=,tag:vOwIc5rflzhXYOVzJftLJA==,type:str]
                      href: ENC[AES256_GCM,data:icZpw/3FLED16U68TOl68vWiQQgMXZi+pVn/Ca9Zvtz/24uOXTP8Fjvhga4MxQ==,iv:exbr7UDW0cpLBgsgt1tHFxLyvTYRlmmx5wK8zzs9KSY=,tag:YhF6X/rjVOYY85fe7k9Zrg==,type:str]
                - Selfh.st Icons:
                    - icon: ENC[AES256_GCM,data:oX4hcFwuVN8nf3C6nPnT,iv:bFN8tb0NWtgNPba46EUHOKK2A9ow3G0y3ljxc7ZZ1lg=,tag:IEI2JhGRVsHsJHo+PUTbsg==,type:str]
                      href: ENC[AES256_GCM,data:Lj8G/T+C3yHeZ+H+Np4cmawuqagSfNA=,iv:MR700KT3IXxjvebSJSqCbzQBt0qplyla3xCuKRBCNiU=,tag:nQlnY2Tf8pcd2zaPxzwCoA==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:Y3d2uXmsJBXENRNl2qhVWF29GVo=,iv:jt8BbI2lNL3xV3lLZ7DIzT68qxhMFe6HYDv2m2UgdrU=,tag:VsRazEAm38oqzB47e5X72Q==,type:str]
                    href: ENC[AES256_GCM,data:wTTCc9r8uemCf25/Y/nRLe0YZBzc/3I0AHF8uGiKv4WtqIOJUnruGsWVqCo=,iv:RF9S7/3Dn3gH+Tbb3VEQIFRPYZTIlzzn1WDUZx5uBcE=,tag:koEaoRnXbDKUxzAYkaa/Bw==,type:str]
                    description: ENC[AES256_GCM,data:mqJWckZpEfGuZ4hTl38m,iv:yTpLNsqEfNj1yM+T2vbkU+VdqWs7SbhCz1gQMPYMpzA=,tag:3cIWD8eod0u4NzAjT0mbGQ==,type:str]
                - Unifi Protect:
                    icon: ENC[AES256_GCM,data:4AidEjp05PxCvox//clYRkk=,iv:f1gV/7YTlBI8BcZTn08/qeKeCyHkzeQF0sB8fblWd1c=,tag:uW3R2dDIGGZllbKcnESpVA==,type:str]
                    href: ENC[AES256_GCM,data:rBoW+YudgU7qJmqHAVib/sCSSbY=,iv:TeHtMWdpvt81GBTGtCRA4ek1HWwpeZPTHl5f1I9mHic=,tag:MLJuT0BY5bu+xYfYdwFBSQ==,type:str]
                    description: ENC[AES256_GCM,data:HnWILp334g==,iv:cW3LkXVZhsc33oICaS3LGEFVK36KXvq2Y3WCj7hFTXc=,tag:yXxeCiIiVR3gS2DL3/l6vQ==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:otuKZUiRTKpIGDHxZQAjjA==,iv:1wJmziwLfUiOLyOZtYZ90MU7ugApXUFK+ADuj4qXsMw=,tag:5y9g4F2+yWrmxt67unraWQ==,type:str]
                    href: ENC[AES256_GCM,data:7YVQs9TB0dXOxiv2y4Tih0LScpqPa6WFnA==,iv:C7wTn0gTlKSfKdtsbnFMXH5ljGF368HpQ34NmSEqGjE=,tag:Rtc/p/+sijodf7t3BpMutQ==,type:str]
                    description: ENC[AES256_GCM,data:lBVh,iv:V6vgbT1pqIhYhDZPTm8cC/XVQLylGjDLD9q3cyU2aeY=,tag:hPtCG8GOY62kmbqn96pF3Q==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:0SMTifscsrJJ5oPj6Mt1EiAvz+UOtpdLwA==,iv:RnQNgLEKhRYNeVffa/SqfiYL7CsbYZnkrByHH1BQ/GI=,tag:lQN2qkLKoof8EXEUyIshaA==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:Oz68aDMXSdrC6NzUOX17cb4GxUxkcw==,iv:rmX9EekFqZH3z74NYgezGL8HLF3+2s6SGZjbE7reH1s=,tag:69hH+FsVBlU5CGGkonvnEg==,type:str]
                    href: ENC[AES256_GCM,data:ytoZKMlGjmYGX1znEzYho8HFWUT9Ugkby40N6BTEJdg=,iv:076CqQN0NDHs5Er0DAJ9hrI8wNOy9jBTUQDXORRt8+8=,tag:AaG1kDaeSRgLq7v+n9BFKw==,type:str]
                    description: ENC[AES256_GCM,data:pROTDBPDqq4tUkzGFFjD,iv:3QM4Wr8yUy8lEOl6bgVOknYgvPrTRUPeKyX8RpWx8YY=,tag:oKwqi14TnsHhpH2y/2+HWw==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:/+VFDKjfySjj/QeGIj8zK8wddrmvHNk7RSb1DxYVqj0=,iv:6jhaOkEJwFKlNbzSjcz/RcOarBzmDnic45HJPfipQlE=,tag:AmBGgTZgm2BTYSUsbK8v6Q==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:yypbV9d/18Dvnn6HOLMQvn6kr8ei,iv:tQWhNkiUHEhDXLs+4bSh67QlSNc9ptvofznDALnCSg4=,tag:eZw94pre384G6aY4+Sgs/Q==,type:str]
                    href: ENC[AES256_GCM,data:dzrGs1tDciFq24kqdp6cbeALpIFRHF3TLsMPrxVeKw==,iv:8QgX4b2HEV9IdiPH+doTzBJ3fW+RP0E9YU4KCjp3oRE=,tag:ZlQma2vbiGVc1qiHA6bPIA==,type:str]
                    description: ENC[AES256_GCM,data:ldFTfdONkdW1Hg==,iv:hjNuV4+YW5zSNrZI/PUBE5GfESvlfp8hxYwwEqcqAUY=,tag:gjtfS0MLsrsAq082m1qmJg==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:U+GjZeZRr7Jvbun+bWU2eU6QoI+CcmVDlQZBQ5TlWQ==,iv:up8UmOhZqzYQ0dpOAgNIbF0CoDA562L0wdqHFZL7hfU=,tag:qiDX4DlGd33i1yUK/Fmi3w==,type:str]
            - UPS:
                - APC Smart-UPS 750VA:
                    icon: ENC[AES256_GCM,data:EnaAvbpq8hfBEg==,iv:9RHchx/cOi+tOTJR0q3k92mFSjXhK50v5BA5RRbjh3Y=,tag:XxWUB18r0IJXFpoLUgMwCg==,type:str]
                    href: ENC[AES256_GCM,data:oN1L+Ji6NkcP1NblaNCqppCUnnuvNnjRgw94nQ==,iv:XpbDh/RNLnKU1sfve+oPa9Di7+FlrVq3OUjEfCKh1Hg=,tag:4PUHldqudJLVfovu3HuSOg==,type:str]
                    description: ENC[AES256_GCM,data:fQBA2AZLc40Kx3EjItUEmw==,iv:A1f89V7iy8wMrG6XFRIRx8F9ln8LaH5Dejn8jjVg4BY=,tag:GUyBAYfVgvQRksT9KnQOtg==,type:str]
            - Smart Home:
                - Home Assistant:
                    icon: ENC[AES256_GCM,data:hxAGluJWsaHdTc7Okmeq2+U7UYjC,iv:tP1EVZTW3iwxAHs5QcYMtbdOT5voa09tx83FmEHZew0=,tag:DXrAmZH7HlhLLYAepq2fMg==,type:str]
                    href: ENC[AES256_GCM,data:4I1v8+Ncuh0lBLuRX0xZFkPkI95wmhriWSpxVR9cHP8=,iv:UHalPTMq1eEaDO4tu7lCwoElTomSX/vlD9WKV4cDFDc=,tag:en17LFTJ876vMdfE1Ab8vA==,type:str]
                    description: ENC[AES256_GCM,data:CjkT9X6I18q/DM3X6Oo=,iv:nBdJ7LAjP/rGX1kDuw65rbvAzDJJEwvk9clZqr6dNPs=,tag:h+yDRD/914VZusDczwLVTw==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:3AGJ9fkLn89O+fMNUj+glKoCtf+NebHOkzk=,iv:5UrDJzJmZeXHrpZcY6eiNEJs8ZZOY3/n8yBTP4iJnbs=,tag:wWLea0h5LkdM9HGbl22lTg==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:KNMX,iv:Tno4bk6fBP4/UgKXSBBEEjhQiIRwvs268BkcyhNx00c=,tag:R1AZ94z3D0oFzsLK3EbfWg==,type:str]
                text: ENC[AES256_GCM,data:ZZAuO8V70Ig=,iv:S9h2XvVpkxfTbspjoWHdpe0a9a2j1FZfs2cdS2Zykx4=,tag:EK0HT1SkiSfRh5Q8ig4MDg==,type:str]
            - ENC[AES256_GCM,data:iIysrxazzENv7u1SapO+hFrY4hIGTuJWhagUlHKjADT2o8pONiYUp2I0Fmuom7kQXrs+S1PdskwtdQCosc7T1SSZg6TbXOWFkDU=,iv:x2nNMKfRRNfZHI4W1XxnH5chEeN5fMfFWsQhe2ZKVPU=,tag:jsU2NGg1ug5zKM6yv3AXHA==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:hXchAQ==,iv:JXZOJaWy40q4wyuD1VdSUZzm2NjO9NrqVFo/3BW6lWg=,tag:59xCsY1bRETZiz9/nOx5cQ==,type:bool]
                    cpu: ENC[AES256_GCM,data:hC1mBg==,iv:Ay+B3ANtWt/bzi1PWgow2kVRaDCZ07SucJp4ZbK/naA=,tag:Xt5ki4aER9xfHP7gVjKs0w==,type:bool]
                    memory: ENC[AES256_GCM,data:QPsaDg==,iv:riWKZbVOOzJVk1rtzuBJ9wmCQLU9BTWsQHZoEfi9exw=,tag:8CzEofDeXPIUyiIjwX3ysw==,type:bool]
                    showLabel: ENC[AES256_GCM,data:KUWv9Q==,iv:aPewEi8Q5PpgXRYE1TD3iKe8Wcd20fGAU/QGQgkB4j4=,tag:Mo/kPMbmc9+sIHA2qxs4Xg==,type:bool]
                    label: ENC[AES256_GCM,data:H+kHIhaeqw==,iv:B9oWp4cOcxnMP9fnt5GTMEMRK1+FpKV5P03owHPU7iI=,tag:CtOzbNauFzrcjlnW92hdQA==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:5kacgQ==,iv:RgQDnnFm8BjN79UOYJcILCEdL2UhLiEuj4jzXxIqxBw=,tag:8T6+kv/G+aDqY6yD1MdKyg==,type:bool]
                    cpu: ENC[AES256_GCM,data:7zmJvw==,iv:n3zYu8BbHYIUmVQHZA84KTMRKaIlozKfPyfAhY8BrFI=,tag:RNpIS9acKNxIj2d+AUD9Mw==,type:bool]
                    memory: ENC[AES256_GCM,data:KwF57A==,iv:xTDJHcsRqjW38nGP/cLLqYtOH4DDWd+bzpuYYcN4STA=,tag:Hn8fVv2QNktG+6uLD18oDA==,type:bool]
                    showLabel: ENC[AES256_GCM,data:pI/YdQ==,iv:s7bNUykdXFOsGIQPrs+xl0a4MiVFTBYdZgDYBb+w4eQ=,tag:vJZCvdylc0qGbSWAmaIidQ==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:jOo=,iv:Y9sHWM3FPYqyQSUWPvVMyq7O8mbHNxSHza55XFieEwU=,tag:CZnT1ARCEU7T8yn2N8sZCA==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:4t5IE3w=,iv:zyL9n3JmW1qxYpuL7s6/nIY3u5QDD/FQQNUFOzpAz1s=,tag:NokaquZjimBomwuwQrzXVg==,type:str]
                    hour12: ENC[AES256_GCM,data:h7OKRw==,iv:IRYnlKJOgdh42PhEifWTF9mppcdhWo8S2FN9eJsvSYE=,tag:Af6ryaFhuNyKXy6rBoEAGA==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:8TI=,iv:fR5pmepjIiRWZZRSPWv95JzvWjN4YAy4/XmBc8RIjSo=,tag:ja0vs3cxn0AjXJ9Uzap5EQ==,type:str]
                units: ENC[AES256_GCM,data:CWaoLb2hYLI=,iv:MU5+PDsAcwExPKBGOlmEYuPmjqXybSfQ1ZxnpngbD1I=,tag:pBOxCQyUtAGVuYafwHkl8w==,type:str]
                cache: ENC[AES256_GCM,data:fJc=,iv:fPXtysP8LNZE+bHnNVUJgtLhMrOsV4ZGiqogLGGvbfQ=,tag:tX5ucRgLh6bqKGrCrJcU1g==,type:int]
                latitude: ENC[AES256_GCM,data:7rXVxv+4wEA6,iv:9dcb7JFoG7TrIcrLFH7IJV6IGhNKyAzn/aRyF7koYaU=,tag:eDQhT4Fz0mGnhtBfl5RyhA==,type:float]
                longitude: ENC[AES256_GCM,data:8Cb/MYyUn3QE2eQ=,iv:QTXJ3DdeHVOP43e9YXFFQFBjT+BobF5bOdGrO4/CEJI=,tag:cw8tyUpdRAgNsL/uZk05Jg==,type:float]
                timezone: ENC[AES256_GCM,data:L2W8yWetaLn7crLhmyKwwWlSUA==,iv:aKWIS/8SpmSj4Y2hQ3FmHsnbTdvE5mVvoisWGlJKvgw=,tag:4Dc3IboMVhgR6n8no5NpnQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ1R5cnV5dFNONk9JbEFS
            T1BsUFg1blFwelRkQlkxK3ZxSVVQN3NmQ2w4CjhOeDhGTVo5M0o3Zkx1TElRRmlE
            a2czV0l5dlpka29BeTQvTk9yU1hmT1kKLS0tIHJzbFdLMmFLMzNIbEtGKzRRb1FY
            K3JPWjhJWTdBK1ROMHAvOXNtbzE1c1kKm48Ne6VOPlJEQZnd9Oj6w27LsBGM1QEK
            jrzvPxpMTY/1rqEsTVzaqb5tHfs9ocfk4p754+ueHVgR0dt1jnrQhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:35:24Z"
    mac: ENC[AES256_GCM,data:pieNPdfN0NhPtKok6t+OaiF+EgzihC9Tr//KdZphztUNu1pU0v8qheG7qP31+R9V3MUHsT4GAA5G1SL8QIYYwqHq5089/syLtOOScwksIvCQIKFlIJt1BrdFr8yfRIU0u3Du9vUeaXKdOC/x8+RBvePkHqOnEriDLW3gQHu5ogI=,iv:WTLkRzFv3uE467x7lXrBGuyay0n7k7GVB1/OhuY1hPc=,tag:nSzy+Qr8co6UD5SwWFth4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
