app-template:
    ingress:
        primary:
            enabled: ENC[AES256_GCM,data:5unofQ==,iv:PmUxpT3Bz4IGZY9Mcxn9eqRrdHm3rwWlYjhVhRfBGnw=,tag:TKJ0NXZFfWQAtHjn7XAUzQ==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Fu1hZhLY2viM9QRcCygfsA==,iv:JSYZOqq4H0N4qYJbF85cVtL6NS4pMPR0f5zbYhtZ4YM=,tag:vORievcHXB6nCgaU4C1k9Q==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:690xEG/ern2iJr0GVFrKm7fze2oNLg==,iv:h/ucgJBg/6p92z/7ZAgscpKP2fpZzE5d1j1CTezaGRk=,tag:jlgGsyUTz5O7Qo6H1n3ZgA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:z6IKckhJMeoss5lCpwlYKDcz3auC0boRCA==,iv:md+CXBCBaGukTqQaaGDeeW3N1G4vb+FsOSHIj1H3urg=,tag:FvCvaNaFw/rDoi3YIWsVTQ==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:KYj8ZQ==,iv:1Y+A+YvSQKb9pUvNuU+5nbfwZFH+XXcYiOrhU4tD4qE=,tag:3eqQZSwPNjXsX+DKo/pOrA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:NgCZOWbLuUqDVCA=,iv:f449nqOpqOI6UAN1F0UcAW0h24ic4AdYqdWw2va5gCQ=,tag:i5Cp04DeOAtj0sAeji2a/g==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:nOwN6cWyMK+PEtcObvRKRw==,iv:1CGeWYaQvzFknrnqqvhJuZ0ZF38QS6qNplujTyoPWQ8=,tag:Bd6KUKrK7NfZ1MlpqIn0fw==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:uQ==,iv:be20NZzwQViVS4SdjVRHtQhlHwQ8KifNRNu+HYOc810=,tag:3J4v3dr8Mqz0OWg1pcFO5g==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:Ul4gsxcfHw==,iv:sEqOsSRIYOQErTIgYA33V5f2GnFJu0n7goT1+RTli+Q=,tag:0JUATZTMbw1fZ4hz8iUm2w==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:4Eq/JFO4Ax72b1VL8ZqnRfqAu4nDeeYYtoU4hmB9nGoAQqMpgyJFGHE=,iv:jZeLIBIJp2NpfspvBy1Ei7dygemjp99KERLb5adxfT4=,tag:807fUvkyIV1/gQsB4FtcaQ==,type:str]
                gethomepage.dev/widget.username: ENC[AES256_GCM,data:lnKiyNvCKg==,iv:rNznrqUn6nXDB/LHRUq9b+44lgOWvtJx5EbCmEZOibc=,tag:oSgatL5/iaNukhlE9QpFEw==,type:str]
                gethomepage.dev/widget.password: ENC[AES256_GCM,data:cViWOVneVjb67SftGANX7PIO0yiaLs0gsjI=,iv:b+hfey4awhTwrjb18mrzErt3AxGf5A4cNDfcQPz8PO0=,tag:sVp5YNk2Yv5YTJBqPNO7vQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:8lg2Q9BzkwdlMy+/Iv0WIMvi,iv:nSBoqkSMi41jMd8/FQHUUDUUSc50S3QlAj/SYys617c=,tag:ECwaWNXDLuzE+vDiJde1qg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:FQ==,iv:EiS3YKkSQ65k3RFPytTjxMRoCz3bwPLCV7fzQbi7Scs=,tag:dmchgWC6r3sJBJyGv0xC6g==,type:str]
                      pathType: ENC[AES256_GCM,data:uUBBL7FQ,iv:JibDny+VIvT1nRdccw/t5Kt/FsnnkT3y11QpXtPbY3s=,tag:55ALqnSBHAt36AsMsmu71Q==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:mlGAXg==,iv:+ZO97UhFWnV2mep9GNMdFtfCYbdx4G68FLx5OPNcSxg=,tag:y4HJXHs3AgoO+VnQ5uZlyw==,type:str]
                        port: ENC[AES256_GCM,data:zPSoJg==,iv:hoWNpJSA/OjGeb/uq2iKwbx9uRujE5e1dnexEv8uxZc=,tag:zSlEc0vMnVWfrVusseph7A==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:/oYAgKevE1FEPV51zkLs27SK917rejpV,iv:Fdg56G6n2EBILttccUb+NuD5P3jiU1Ps/ps9IoZGiTc=,tag:jHbAsLD1DUyCXwqqyzuSxA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:acK2nLuCh6XCWBS+A3UE+Cxg,iv:TsitxqhqPtjzNb589YwUQf0lHaV+2QHUrGGMn/b7zSA=,tag:bVf/ei4PJIZto0w7KwOiUA==,type:str]
        secondary:
            enabled: ENC[AES256_GCM,data:UN15hg==,iv:kjBIQ/kU+zk+Y/5Vs7mpA0c7dcxWMyQ3uNd7A6oyDy8=,tag:xuNLmUPGCzlbgoc9Jl9zsg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:kJusqr7lRx0Wvsx10mBEqA==,iv:XEVZW5j/ZmQjgpBbrcJSKmAyVEgC5HLYt0mY0Bl83yc=,tag:6M03ReF6vrmeZEb5kZPrpw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Wl5MXcluBqE2ORHVMlb6e7eXrLm8q/KN,iv:nv6Q7yiqiVndnbDGG7mKaAyznSLUi5Oq9tYpQ8vs6Kk=,tag:JvyIWv5W0zgnE339ORaOSw==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:VA4Aaq1YYlzW3xU/2EjcoLUYurr4BrKLAA==,iv:yaS59Kv31WYtllP6KAzThFr5QWYSrmNA3oNS0DmZgIk=,tag:C+kS0RFM/nvN2bp3Pg7Mkw==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:Bhjxbg==,iv:1YcppdiPbrw9S/uFM/yaIy8Y59Wj08XxhU1j19YQ4HQ=,tag:kPe+J2/Rt7jaa54F92PtyA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:z4kCsjRhMHaKk/4=,iv:6Yb9Qj9qxEbMHHkQov8kzfg3j3m6MfCisTKIESt3GDs=,tag:TUHZg9Yzt182NEFXLbX1hw==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:Cg633mMzE+tTUL3vFqddQA==,iv:K+TYXAxFaqtGyDl6vIvdVTKESYA6iXNz5J95jy19NGo=,tag:dVqp6oPbOGr4EAANjzYiTg==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:vQ==,iv:fRfHMVFJ02tdNaUTL8WynLNi/kFmD3PDIMv5Ei6fSr0=,tag:IP0ir+eW1i+VMc7pr4VnMQ==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:9raOoncfdg==,iv:MglgISAwob9CIHHRyRI5bMAUZLH7ld78d3zE8M6JWDc=,tag:l9eLLJEMeIR3U8eJmznVHw==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:x29H9efcv/WfkjHAFTAMzcpUUfNo5Cj1QvCiwBy5044jEWMvcF1FMPpXGFc+Gw==,iv:qqMRzK38h61qoQCRaM8uGMI1Np9beCh6Bb7j4zSV7I8=,tag:9v/T67/RvoZRzmScp/+Bnw==,type:str]
                gethomepage.dev/widget.username: ENC[AES256_GCM,data:kR/lcJJAQA==,iv:IpmTqM2Bq40Mg3WVkIqZQiGubsjznJFaPZpE9OIawkQ=,tag:6xPnH8GGZYlmDpxlWXXnFw==,type:str]
                gethomepage.dev/widget.password: ENC[AES256_GCM,data:SbQ1DWqRuowwvJuQBSr/WyFGo2D6cIn4+j8=,iv:16adH6jkJr+f0Ojbpfk+BaznqcK2sbvcvTvLeX+JmTg=,tag:uX5RQAHmWiJ8ffk9MbITLg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:C2ds+YsPmtj8bsGzyYuQsy17,iv:hDHC+3vRp/hM4qx/JBGeUo3K7Hi8wgmcsOyeSHB2SX4=,tag:eNUCy3W3XUuDnQQbh8yLGA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:+Q==,iv:synILZAuMyPdA6NXsZoD6EU7DHPzirsbyiBGCtKisx8=,tag:U+c3cSHCiUR4ATYxOjYN7Q==,type:str]
                      pathType: ENC[AES256_GCM,data:JT0w1hfs,iv:VkTMXaddw3p31/Wg3jOsXB5ikMzxp97rdqzFpgWFiec=,tag:LLD1gNrEGSxpCv4On3GzDw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:YyiPPeNGPj/d,iv:7RUi42GXJVQ24n0dEYIesNU198Y2tF6a13avnzwU6Ok=,tag:ofzmRVL1Cp0Xr4cRdIACjA==,type:str]
                        port: ENC[AES256_GCM,data:m7+TyQ==,iv:Tcm1qejWEmxRuBHhLMIJ61MNdkdGoLHzpGKxOfQqtjQ=,tag:Bk4AbHJQlJP+Kh4wMjwzKQ==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:DHDufaTjJARIjNg5meazY6W3kX6y5lpZ12w=,iv:Sl3phQwl6BvFQYcHs5cLKkB1+gOSlcf9vX6DfE5YU7k=,tag:z1un4vtXxeekLrU8S1rspg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:lmuoYuoyKiFkxmwz5n8kz2ea,iv:tgu60qyRz/lEUoWOzo9rN4y+AcWBQX+V9tS4sa3oRNA=,tag:y1SuS/w1VAu4leMz7M9GJQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dXJ2M2Z0a0NySDgyY21E
            WXBwci90dzZneW9RVHhIczduSTByQ21jcG0wCjhVcG5ic25HRFNhRmdwcVVFK21M
            ZEN5Tnd2QUc2bVpmekpOT09HL2VRL1kKLS0tIEM4Ti9UZXlOOVRBWkJrM3ZIelJq
            SURud3JRdXh2UXgwWmI1Zmc3QUpNSTAK5bE029/RHwqjCbOhDdWwHKL/HI5HJxK+
            TMNPy+NsC+ZXjO6W+365Q4jCuPjarqd+DnCEMcei1aV5SfhYPirAYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:16:11Z"
    mac: ENC[AES256_GCM,data:tuY4eYsuXIMdvZKybk1bIp3s3g9WkZ+dLWm8vuEew+1dhImr4YnzA21SnEO3rUwbL5kpCnJcbhNdBD+E59CuoXJw1FAOW7lbZZWSb/lc2GvT3gNTTfLo4ZIVZppHDKn5zt76PXZluvCqKGLfKrqBd1KnAia4p46wlAmcMVQefxw=,iv:9ctQeRh9PxfWK+M6vT0NbQCe+0zMPizVRzamwxSXMgs=,tag:fpeoGVIkbTAkraMmZVOwAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
