plex-media-server:
    ingress:
        annotations:
            gethomepage.dev/widget.type: ENC[AES256_GCM,data:GsiwUQ==,iv:r2S73ODP2/HgXZ9SRnXOKOaHxQQCX4XNkYb0nAbJOWQ=,tag:Gz6MLyahlF23zlKMJarwGg==,type:str]
            gethomepage.dev/widget.url: ENC[AES256_GCM,data:nPzkdvfcOyetG2waRVMM4t8wsPc=,iv:U/q5yaWOYTFoUmrt/jVSUNZo443Y8Spsp5kkde2E/Hs=,tag:lc3FoysYrJbwKu/fOmLTlg==,type:str]
            gethomepage.dev/widget.key: ENC[AES256_GCM,data:xb2xPkWHmaYROhbSyhxbfpCmc8E=,iv:0TERKl0rmGHuAuMx1+slnLFZCb2n8ZKiOYes/W+CwG8=,tag:5Ytalh5anWqzG1OVtpjTTQ==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMGdxaWtONkpyOTQ4Mks5
            c20ybUd4ZXZGaWpyaXQ5WTVuNVlmd1NYVXo0Cm5HV3c3QmlYbGtja2lJMktGVnhs
            TysvUXFHcm80bVpoc2h3WlJPek4vNFUKLS0tIHZseFl5OE4wVXcrRHBiak9WNGxu
            ZXowSmVsakRNRDNTUnk3bDU1TUs1TkkKLHpVQAipEWYW9qxUWrEYeiFWQf3Y5ICa
            2Z2in2+xgazCkhHQSNQVhtgTGIy78GNJ1x2qwPFJIsNtZNdJisYEbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T19:57:09Z"
    mac: ENC[AES256_GCM,data:1Z1COM34uSYT8ycG85MZWFNkEdZskR99V/vXCgYjt1jEu00ULky0F1JpIHrBORvRPmpcJ2hAT9nMQzgCKyEVq99rvsAeYKnZ243ozCiXXo3+UjU5V419jWrXG3p0ckj2PofTTlCGxWn9S4jGb+JjFwJoPvIN/KPamPzda6yC/X8=,iv:eWEJ+0WGVi/evMgh6cWw1iFvT5JlUGJ7Xxa6jYSZqic=,tag:Xl9nJAR/PyWaYyo5V7F4tQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
