plex-media-server:
    ingress:
        annotations:
            gethomepage.dev/widget.type: ENC[AES256_GCM,data:pPehlw==,iv:F961fwDOjjKQ+8p/WnNsPZkv7M40u0oQcslkPU1L3cE=,tag:pY8rEam6Q+aaTJs/w28mQw==,type:str]
            gethomepage.dev/widget.url: ENC[AES256_GCM,data:c5VCShewX5Xi8RY4XtDg3AXXIA==,iv:auXkjHUNn1AxvC9U/EmYFfqouVru0TVSa+wRhHD/5eY=,tag:ZmQWR4nN0CLUudDr1v7Thw==,type:str]
            gethomepage.dev/widget.key: ENC[AES256_GCM,data:QeTpQBQLZ/2GlXvXfcCUS3utNfc=,iv:fSxo1w3FLdekXW+NCUu6lIe4K34agf53Pxd+6AmgL5A=,tag:yInGprwGDZ2bqmUU2hrhjw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbzh0ZkhIcHViMXMrakVT
            VHZhMEk3VUlWSUE2Rmp3SS8xNU5zSE9oRHdnClR2TEtSQllaemtNM01zeVpWT2dW
            V1FMdUYzZVBPUmRBeFdaMmxQS1J4RDAKLS0tIHh2WmNnek1RSEp5WlN1MUNZYlF1
            Y0ZaMlB4VGoybWZQRTk3R2MyOG50SkUKZVwUn6j21GToTxq5dIQDRLxs0Zp2WB+v
            ggEWgLI+x7LRcwmWOVp7cHwqSnnBsM4DfkOWe5P2dpNr1jnqYROjFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T20:00:19Z"
    mac: ENC[AES256_GCM,data:zqkvo60c61t7F3Goqay0fbKCRs6BW/lycmrll5SdEfWvPGiWqnV7Li1UDKOrdZzl3uPZycDuCp+EFmpRxZY98GL/nxaOqi09pG6hLaX+rLEKNm4uAftbcrz51X2/cQQlF5bPyYiutwba+5Tq1fDE1JkPrHlv9Hr3GEydZKQ14/w=,iv:T2UPtQMwt+QFXJ4fVcxKI8l0GEKn4SkH4MpUd7gpSMk=,tag:yAxhTsIGp4MkVbzL6G17hQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
