app-template:
    ingress:
        myspeed:
            enabled: ENC[AES256_GCM,data:W7nl7g==,iv:4vYfI2GJGOo0Oe/vD1TjGzPd2CzVsuNBoc8s52r4Kpw=,tag:QuSvlMCbl+EpqvRJ6IGCXg==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:3WPIQap7ptxPDQisGf31fg==,iv:h4ubHsFlOIPv6gG63QE++oDhEr9NcvZiCmAR6iRLjIE=,tag:aSyxb6Nb7NdCxaMXfFh92A==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Qs6hG0Z/BQ==,iv:Hg/8ahlUTHtLj3BNEvmJB9bIhnn6LUFxITIIvASzR60=,tag:wbUCd+5+aieY0TpacLaqSg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:ZNPUJotb2wq/dQ==,iv:x4RG5VIF+Pur0Sab3+UXGdd1Dq0Ypp+FxqZ0+hzIho0=,tag:tm7q9YCY+SXVHBLYinvOdA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:s+myKQ==,iv:jqgTWDKkd4YNG9MYDSqHLyvdPpZ1+R1rJtv9E3FV3Uo=,tag:OH8SZMvqkRAuDHtADF4clA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:1qMU0h2wgfA0Ac7seg==,iv:C8jHv7j5P0P4BKaeADwYe4947BJZzzaDlwLfvCT8+FI=,tag:b6mP0/04M73VjFdFmtXgMg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:9lO0wchDIXwcQ4ZiVPk=,iv:3mhtFUaJsSTU2mrSDoFbLSD1xMScrtlGSSXR+c/AX0E=,tag:Zjuk4wRvSyciOX02+dGAUg==,type:str]
                nginx.ingress.kubernetes.io/proxy-body-size: ENC[AES256_GCM,data:NfmB,iv:joLILPcWXycSQVZnyNIBpct9zDE3rvWhvl9auuxTcc4=,tag:Dun7aYIapixOL71iwOdUOw==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:m74=,iv:zWQCvpwrJdyj9eeAjlr5BLgxAgAI1zthzjjIF18t/EQ=,tag:Q5GGW424Gx0p8xPUTRq0Kw==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:RfdwNRyPfw==,iv:YlNM1Pf/YjGrbZ+zvd6GUS36vcbA4CvqMyIwv7ohM+M=,tag:NN9WE+LCUfNBszSZwqnLxg==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:Wy535j4s5EsheF4w4Yf1gATkhjrgFCO88Wcr,iv:n/z8t2CKeAEVEyQEghuRnjZu7/kTGulVhNGen2dFuG0=,tag:796SkAekebVjTow9+v6ECQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:vgvywhSw/rYEmtj/Ze82bAyBIQ==,iv:amO3KEakzR4nGZaOmp1UVoN+aQIItCJfI1qD3v/GeWE=,tag:yy8MAk1xiA3EyMdky2bH9g==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:FQ==,iv:zMs0O39CmAnpgnQC9rN3tdYXGyHk91dZyJFvrSz7Hcg=,tag:J0zZwGsxumwpTMZk8finQA==,type:str]
                      pathType: ENC[AES256_GCM,data:bf1RMnMZ,iv:IUadfaVQo1xN6yt9b3eXux/TrAhWANHfB2cSMwWGEgA=,tag:QYvjNgQqAUMAfGOLPGlz3A==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:+kbdQki0UA==,iv:0gAEmoB9pA2zqD/1iW6A6a6GSJ7QT8oPH0KLdlrELiM=,tag:jg3aG++ttyR1K1JE+kqMBg==,type:str]
                        port: ENC[AES256_GCM,data:BLdUOw==,iv:hY+4F5J3zmeVhz4nCInYfSqxkty7j7JqTnwfb9xnyoA=,tag:vF1I4DQigykXK7VgZupAeA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:UxmBGcD4ch2OV7iAZw98fQ==,iv:pWpLU3zaxO+s5NMzH6fr1la/RDc/YTB48QcDMeVFSfw=,tag:GAWY5jxPENmD/g7b571erg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:D68B5N3H0CX/vHmEgdDhk60KhA==,iv:dTGHGNYmU/QNkIJxm1xNCE7JvBez3i+YOU2CXMKKzVs=,tag:bNyEoxXFcFKaRMgVxbVV+A==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVjM4V3kzUHZEWk5jbkE5
            UytZUHdER0preVBWeWhJMm04MHVsSkpRT1RVCkxUTnFwYVBxREZEU0J4RjBscHNt
            eU5jSjRPclRucmlHZFYyMXpzQUJkODQKLS0tIFRMa3RHWFBGZXBlRTFQMlA0R2lt
            QVNJaXUxa1NSRWxmcGt3TVJVM2M0bzgKEXJp5imwYBI+xYNngPLUIuef1xJSkp5+
            j5gJQuhMeyKkxP++igBAK7aUlBlw5FNv6hFD/7dIi1uwL9cwZynOLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:12:08Z"
    mac: ENC[AES256_GCM,data:xccWIL7G0YHeF1pIXZmHIdh6RNZzkaOCQcGnZg+P7GLZaBE7VufH1dtrk6UaY4MkpJv5cjecDt1MPvBAEcidox7IsybTYRiPTEgLbW8sbssd+yVvNnyIfKtMhtcWEnnRYFhlOBAlj53cPoVERggypJdqj/LqgrTNDmG3yjZwZIM=,iv:Abu02hg+/N/xAYF2Jl8huXzDKJjGen+M2hdSESDDRsg=,tag:hw9zo4rgYfzh6Ff7B92iPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
