app-template:
    ingress:
        myspeed:
            enabled: ENC[AES256_GCM,data:on/t0Q==,iv:70LeO76uhCBv5u4lsojiUgsk3mOpTDQelYYIntxQ1d0=,tag:bhWJnRS4xeUVp++m8IJa+g==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:jc461eki0wvgMlHqlcSh0g==,iv:MBvyhhLSK4vWbm9gx1JzFY73WxwvGNNrNjB0IDn8krg=,tag:7ILv3o/h3uMZ1Sz5ZsbpbQ==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:u0fB9HBPrg==,iv:/xYTTsnqa2T9p1Zf+QhL7Q7X3Pcgux6ELeg54z3tw9s=,tag:hdMBwGNKMWn8bXlt9cx7OA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:k6jxzgt0isjKrw==,iv:EBQ4BUlhFAJbxmRj3JIO52ylew9iIXraEztPo1frp/I=,tag:PrC1M0bHhgp79HG511wgBg==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:p1HsVQ==,iv:oZ7/K5mgWQ9bh4z6XbqxRs0frpxRaUSo3IgPt5I3RP4=,tag:3eYnw2+3K4H2V5rov9T9Lg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:Bg3M4CbPINUZgsOYrg==,iv:6E2JD9hxBW5QWTU9SurowqfK2nvhUn1/40uYKuZ3I88=,tag:HomuRpCOR21MufO/PeXCWQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:1JzxOpsPMSieGVwO7Xs=,iv:3qOX3o6tkx/N7vVdkFOEoqA9TKTa+WG/e08u5RUxDkM=,tag:DSWgmhLW1+gBFx/S5hdOcw==,type:str]
                nginx.ingress.kubernetes.io/proxy-body-size: ENC[AES256_GCM,data:xaR8,iv:KcDl/dXnb9vABb3WNmTYY0WglV4URCX8YTODRVwJH5k=,tag:x/zDyrO+4lS6hXLfNdCeCQ==,type:str]
                gethomepage.dev/weight: ENC[AES256_GCM,data:TcQ=,iv:FQTCS6I9AMR1pew3VKBDRMvX/VHQUinmGzI4rIw1voc=,tag:IXDfk6r9SPoPbKGvheoHOw==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:lWgXSdQgGg==,iv:SLXNQW09s5uNZIcTON2HbN/DxWpZk8mEhwJfkz/Rdqg=,tag:ldSTFUuFyv6yfIfYHKcqaw==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:QXfZfyjOIJR3VV7B7KXJpD+vxBc0qlbnbMjxneDbmQ==,iv:SVRG2T8unItyhFsV+5po8CKldQPGRNmc7K17vOLB2bk=,tag:8ElvjB7eGZl2zNywkRPXAw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:dfocyu1Lxlt53AY2mahVP0qaVA==,iv:kVGXdjGKxw1iT9IhOZbE0AOkUORLKUuW5bpXZIQsMNA=,tag:IvOtwZK/qutPfp3UsWOgoA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:fA==,iv:5UhiUUM/Gn0og8uQzSGm3xjhQGTU2SNTSL1v23K2Zhc=,tag:kJqwjmB2U/qFvQ+xBxrsaQ==,type:str]
                      pathType: ENC[AES256_GCM,data:UJFGF4aG,iv:OYQS0Txw5JC9s7ecUG7yFSm7PrxbWRBRkeSUq+lBDfY=,tag:HUxPi1vyhOKKMpQ6BZrgjA==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:+aTLJP8lCA==,iv:H21NMZAqHTCzLnrcrt42ksNrQtTQYI/j913tkYGqTKo=,tag:9+0Of/4xiRi0mN/P1Ds68g==,type:str]
                        port: ENC[AES256_GCM,data:cdWqTw==,iv:M4GZQoAFaYhQLNfrHw5GDHQNfAwyxTJCkdBcylXztkM=,tag:ABHqgzaJvK2lRBIi2fPXnw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:Cf0t/dUSrNkY3PCKLFiGyw==,iv:RHEsuNsYEBw9TnB7RedtxJyhW6Xh7PuxGstxVeAwUKc=,tag:qCnnOVtqSD6CyGkzmb6VHg==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:r05RsrNLbARyirdxEbxiZTCrNA==,iv:pPUBvQcg4j6Rjxsi/Z51LMIhUlYLI20ZDsRXlz3YiWg=,tag:2QM+qtiuqgxu19Bv/2TMWw==,type:str]
sops:
    age:
        - recipient: age1zkfsdxrlz4aqqd00qap7hksakc8jdkzwkmqs3p85fkw75xls6q0sy37l5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdmpBeG5WemVjTnRjRkNk
            RkMyT1VXV01mMEIwVjBrdUpyTnNpVktjbHc0ClZUNTE4ZjNnTi9pSktYQm91NzFL
            dnZ1SVA2QXB0bXBaRlZJRWgwQ2g4cUUKLS0tIFh6aUp1V2I0RmpTcTBJU2FKWWVS
            Y2FRRW1HMHFXSWN5dmRYamp1d1hOaHMKK154C2kcNYHqvVPaTXf415To5xkAKju+
            dNILPFjKb9NCgnlV2bxSisjcV58+av6OPrpL5bzONrs7td4m5ki6Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:14:26Z"
    mac: ENC[AES256_GCM,data:mc6dg2j1clk8yo+Mtjsvj8HOBDz4htUkABjOT71OtEUhmLR2m3H8IviOFfN+Xp+Xm+vpVpXK+ozBVA3BuKlL6TUNoKgjni4tHgKpaoTEWuFYgVBFixjOPGMJZPAmTIwX3+jqeuN0HDGRLhuzg/CfA362nmyNioeNZdGU/8rkh0g=,iv:9gwwXdvBcFN0NIUJkbhqGDcMLnQ/s4a9jPavsbFGcJc=,tag:BSriqbPBd/SJAMQmJkZntQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
